/* ---------- Kalender: statuslinje og analysepanel ----------
   Bygger bare på det Salong har: saker med dato og rom, og importerte bookinger. Ingen oppslag i bookingsystemet.
   «Uten registrering» betyr at Salong ikke har noe den dagen. Det er ikke bekreftet ledighet. */
UI.calRoom=UI.calRoom||'';
function calEntries(){ const out=[], dOk=d=>d&&!d.deletedAt&&d.stage!=='tapt';
  for(const d of dealsOp()) if(d.date&&d.room&&d.stage!=='tapt') out.push({id:d.id,kind:'sak',orgId:d.orgId,label:orgName(d.orgId),title:d.title,room:d.room,date:d.date,stage:d.stage,value:dval(d),ownerId:d.ownerId||null,attendees:d.attendees});
  for(const b of bookingsAll()){ if(!b.date||!RM[b.room]||!(b.status==='bekreftet'||b.status==='forelopig')) continue; const d=b.dealId?S.deals[b.dealId]:null; if(dOk(d)&&d.date===b.date&&d.room===b.room) continue;
    out.push({id:'b:'+b.id,kind:'booking',orgId:b.orgId||null,label:b.orgId?orgName(b.orgId):(b.organizerName||'Ukjent arrangør'),title:b.title||'Booking',room:b.room,date:b.date,stage:b.status==='bekreftet'?'bekreftet':'holdt',value:b.value,src:b.sourceSystem||'',attendees:b.attendees}); }
  return out; }
function calStat(keys){ const [y,m]=UI.month.split('-').map(Number), days=new Date(y,m,0).getDate(), E=calEntries().filter(e=>e.date.startsWith(UI.month)), by={};
  for(const e of E){ const k=e.room+'|'+e.date, l=e.stage==='bekreftet'?3:e.stage==='holdt'?2:1; if(!by[k]||l>by[k]) by[k]=l; }
  const wds=[]; for(let i=1;i<=days;i++){ const w=new Date(y,m-1,i).getDay(); if(w!==0&&w!==6) wds.push(UI.month+'-'+String(i).padStart(2,'0')); }
  const per=keys.map(k=>{ let c=0,h=0,d=0; const free=[], lv=[]; for(const ds of wds){ const l=by[k+'|'+ds]||0; lv.push(l); if(l===3) c++; else if(l===2) h++; else if(l===1) d++; else free.push(ds); }
    const runs=[]; let s=-1; lv.forEach((l,i)=>{ if(l===0){ if(s<0) s=i; } if((l!==0||i===lv.length-1)&&s>=0){ const e=l===0?i:i-1; runs.push({from:wds[s],to:wds[e],n:e-s+1}); s=-1; } });
    const gaps=wds.filter((ds,i)=>lv[i]===0&&i>0&&i<lv.length-1&&lv[i-1]>=2&&lv[i+1]>=2);
    return {k,c,h,d,free,wd:wds.length,runs:runs.sort((a,b)=>b.n-a.n),gaps}; });
  const T=per.reduce((a,r)=>({c:a.c+r.c,h:a.h+r.h,d:a.d+r.d,free:a.free+r.free.length,cap:a.cap+r.wd}),{c:0,h:0,d:0,free:0,cap:0});
  return {per,wds,E,T}; }
const calDay=s=>fd(s,{day:'numeric',month:'short'}).replace('.','');
function calSideHTML(keys,St){
  const sel=UI.calSel, todayS=iso(new Date()).slice(0,10), one=UI.calRoom, E=calEntries(), row=e=>'<div class="li q"'+(e.kind==='sak'?' data-open="deal:'+esc(e.id)+'"':e.orgId?' data-open="org:'+esc(e.orgId)+'"':'')+'><span class="dot" style="--c:'+ST[e.stage].c+'"></span><div><div class="t">'+esc(e.label)+'</div><div class="s">'+esc(roomName(e.room))+' · '+esc(e.title||'')+(e.kind==='booking'?' · importert booking':'')+'</div></div><span class="cal-st">'+esc(e.kind==='booking'?(e.stage==='bekreftet'?'Bekreftet':'Foreløpig'):ST[e.stage].n)+'</span></div>';
  let h='', u='';
  if(sel){ const L=E.filter(e=>e.date===sel.date).sort((a,b)=>a.room.localeCompare(b.room)), free=!L.some(e=>e.room===sel.room);
    h+='<section class="panel cal-p caldet" aria-live="polite"><header><h2>'+esc(fd(sel.date,{weekday:'long',day:'numeric',month:'long'}))+'</h2><button class="btn ghost sm" type="button" id="calX">Lukk</button></header>'+(L.length?'<div class="list">'+L.map(row).join('')+'</div>':'<p class="empty">Ingenting registrert denne dagen.</p>')+(free&&!readOnly?'<div class="row"><button class="btn primary sm" type="button" id="calNew">Ny sak i '+esc(roomName(sel.room))+' denne dagen</button></div><p class="meta">'+esc(roomName(sel.room))+' har ingen registrering i Salong denne dagen. Ledighet må bekreftes i bookingsystemet.</p>':'')+'</section>'; }
  const up=E.filter(e=>e.kind==='sak'&&e.date>=todayS&&['holdt','tilbud','visning','dialog'].includes(e.stage)&&(!one||e.room===one)).sort((a,b)=>a.date.localeCompare(b.date)||ST[b.stage].i-ST[a.stage].i).slice(0,6);
  h+='<section class="panel cal-p"><header><h2>Kommende hold og tilbud</h2><span class="sub">'+(one?esc(roomName(one)):'alle rom')+'</span></header>'+(up.length?'<div class="list">'+up.map(e=>'<div class="li q" data-open="deal:'+esc(e.id)+'"><span class="dot" style="--c:'+ST[e.stage].c+'"></span><div><div class="t">'+esc(e.label)+'</div><div class="s">'+esc(calDay(e.date))+' · '+esc(roomName(e.room))+' · '+esc(ST[e.stage].n)+' · '+esc(ownName(e.ownerId))+'</div></div><span class="cal-st">'+short(e.value||0)+'</span></div>').join('')+'</div>':'<p class="empty">Ingen åpne saker med dato framover'+(one?' i '+esc(roomName(one)):'')+'.</p>')+'</section>';
  const mx=Math.max(1,...St.per.map(r=>r.wd)), sorted=[...St.per].sort((a,b)=>(a.c+a.h)-(b.c+b.h)||roomName(a.k).localeCompare(roomName(b.k),'nb'));
  u+='<section class="panel cal-p"><header><h2>Romutnyttelse</h2><span class="sub">hverdager i måneden</span></header><div class="cal-ut" role="list">'+sorted.map(r=>{ const used=r.c+r.h, p=x=>(x/mx*100)+'%';
    return '<button type="button" class="cal-u'+(one===r.k?' on':'')+(r.k==='solstad'?' sol':'')+'" role="listitem" data-calroom="'+r.k+'" aria-label="'+esc(roomName(r.k)+': '+r.c+' bekreftet, '+r.h+' holdt av, '+r.d+' i dialog eller tilbud, '+r.free.length+' uten registrering, av '+r.wd+' hverdager')+'"><span class="cal-un">'+esc(roomName(r.k))+'</span><span class="cal-ub">'+(r.c?'<i class="bekreftet" style="width:'+p(r.c)+'"></i>':'')+(r.h?'<i class="holdt" style="width:'+p(r.h)+'"></i>':'')+(r.d?'<i class="dialog" style="width:'+p(r.d)+'"></i>':'')+'</span><span class="cal-uv">'+used+' av '+r.wd+'</span></button>'; }).join('')+'</div><p class="meta">Tallet er bekreftet og holdt av. Klikk et rom for å se bare det.</p></section>';
  const W=St.per.filter(r=>!one||r.k===one).flatMap(r=>r.runs.filter(x=>x.n>=3).slice(0,one?4:1).map(x=>({...x,k:r.k}))).sort((a,b)=>b.n-a.n).slice(0,6), G=St.per.filter(r=>!one||r.k===one).flatMap(r=>r.gaps.map(ds=>({k:r.k,ds}))).slice(0,6);
  u+='<section class="panel cal-p"><header><h2>'+(one?'Hull i '+esc(roomName(one)):'Lengste hull')+'</h2><span class="sub">uten registrering i Salong</span></header>'+(W.length?'<ul class="cal-w">'+W.map(x=>'<li><b>'+esc(roomName(x.k))+'</b><span>'+esc(calDay(x.from))+(x.to!==x.from?' til '+esc(calDay(x.to)):'')+'</span><span class="cal-st">'+x.n+' hverdager</span></li>').join('')+'</ul>':'<p class="empty">Ingen strekk på tre hverdager eller mer uten registrering.</p>')+
    (G.length?'<h3 class="cal-h3">Enkeltdager mellom to bookinger</h3><ul class="cal-w">'+G.map(x=>'<li><b>'+esc(roomName(x.k))+'</b><span>'+esc(calDay(x.ds))+'</span><span class="cal-st">1 dag</span></li>').join('')+'</ul>':'')+
    '<p class="meta">Dette er dager uten sak eller importert booking i Salong. Det er ikke bekreftet ledighet. Sjekk bookingsystemet før du lover en dato.</p></section>';
  if(!sel) h='<section class="panel cal-p quiet2"><header><h2>Valgt dag</h2></header><p class="meta">Klikk en dag i rutenettet for å se hva som er registrert, og for å opprette en sak på en dag uten registrering.</p></section>'+h;
  return {side:h,under:u}; }
{ const _h=V.kalender.html, _w=V.kalender.wire;
  V.kalender.html=function(){ const view=ROOMS.filter(r=>UI.calAll||r.nw).map(r=>r.k); if(UI.calRoom&&!view.includes(UI.calRoom)) UI.calRoom=''; const keys=UI.calRoom?[UI.calRoom]:view, St=calStat(view), T=UI.calRoom?(()=>{ const r=St.per.find(x=>x.k===UI.calRoom); return {c:r.c,h:r.h,d:r.d,free:r.free.length,cap:r.wd}; })():St.T;
    const [y,m]=UI.month.split('-').map(Number), title=new Date(y,m-1,1).toLocaleDateString('nb-NO',{month:'long',year:'numeric'}), imp=St.E.filter(e=>e.kind==='booking').length, tile=(k,v,s,c)=>'<div class="ku-t'+(c?' '+c:'')+'"><dt>'+k+'</dt><dd>'+v+'</dd><small>'+s+'</small></div>';
    let base=_h.call(this).replace(/<section class="panel caldet"[\s\S]*?<\/section>/,'');
    base=base.replace('<span class="note" style="margin-left:auto">','<label class="sr" for="calRoom">Vis tall for rom</label><select class="in fsel" id="calRoom"><option value="">Alle viste rom</option>'+view.map(k=>'<option value="'+k+'"'+(UI.calRoom===k?' selected':'')+'>'+esc(roomName(k))+'</option>').join('')+'</select><span class="note" style="display:none">');
    return '<div class="cal2"><dl class="ku-kpi cal-kpi" aria-label="Status for '+esc(title)+'">'+tile('Bekreftet',T.c,(UI.calRoom?'dager i '+esc(roomName(UI.calRoom)):'romdager')+', hverdager')+tile('Holdt av',T.h,T.h?'venter på bekreftelse':'ingen hold')+tile('I dialog eller tilbud',T.d,'dager med åpen sak')+tile('Uten registrering',T.free,'av '+T.cap+' '+(UI.calRoom?'hverdager':'romdager')+'. Ikke bekreftet ledighet')+tile('Utnyttelse',pct(T.cap?(T.c+T.h)/T.cap:0),'bekreftet og holdt av'+(imp?' · '+imp+' importerte bookinger er med':''))+'</dl>'+
     (()=>{ const X=calSideHTML(keys,St); return '<div class="cal2-g"><div class="cal2-main'+(UI.calRoom?' one':'')+'" data-one="'+esc(UI.calRoom)+'">'+base+'<div class="cal2-under">'+X.under+'</div></div><aside class="cal2-side" aria-label="Valgt dag og kommende saker">'+X.side+'</aside></div></div>'; })(); };
  V.kalender.wire=function(v){ _w.call(this,v); $('#calRoom')?.addEventListener('change',e=>{ UI.calRoom=e.target.value; renderView(true); });
    v.querySelectorAll('[data-calroom]').forEach(b=>b.addEventListener('click',()=>{ UI.calRoom=UI.calRoom===b.dataset.calroom?'':b.dataset.calroom; renderView(true); }));
    if(UI.calRoom){ const th=[...v.querySelectorAll('.cal tbody th.room')].find(t=>t.firstChild&&t.firstChild.textContent===roomName(UI.calRoom)); th&&th.parentElement.classList.add('focus'); } }; }
