/* ---------- Kunder som arbeidsflate for markedsbearbeiding ----------
   Listen er fortsatt hovedformatet. Ny er at hver rad viser relasjon og bearbeiding hver for seg, hvem som har ansvaret,
   og hva neste steg er. Markedsdekning er en egen visning av samme data: hele målunivers per segment. */
UI.k3={q:null,seg:'',rel:'',mkt:'',quiet:0,card:'',tier:'',view:'liste',sort:{k:'pri',dir:-1},sel:new Set(),busy:false,msg:''};
const K3_CARD={tildelt:'Tildelt',kontaktet:'Kontaktet',dialog:'I aktiv dialog',ikke:'Ikke bearbeidet',mine:'I mitt ansvar'};
const k3Worked=r=>!!r.la||r.deals.length>0||r.rel==='parkert';
function k3Pri(r){ if(r.rel==='parkert') return -500; return (({A:300,B:200,C:100})[r.tier]||150)+r.score+(r.nba.over?150:0)+(['tilbud','dialog'].includes(r.rel)?60:0)+(r.rel==='bekreftet'?-80:0)+(r.ownerId?0:20); }
function k3Pred(){ const K=UI.k3, q=K.q==null?UI.q:K.q, a=actor();
  return r=>(!K.seg||r.segment===K.seg)&&(!K.rel||r.rel===K.rel)&&(!K.mkt||r.mkt===K.mkt)&&(!K.tier||r.tier===K.tier)&&ownMatch(r.ownerId)&&(!K.quiet||r.days==null||r.days>=K.quiet)
    &&(!K.card||(K.card==='tildelt'?!!r.ownerId:K.card==='kontaktet'?k3Worked(r):K.card==='dialog'?['dialog','tilbud'].includes(r.rel):K.card==='ikke'?!k3Worked(r):K.card==='mine'?!!a&&r.ownerId===a.id:true))
    &&match(q,r.name,r.segment,r.rel&&U3_RELN[r.rel],(r.contacts||[]).map(c=>c.name+' '+c.email).join(' ')); }
function k3Cards(D){ const rows=D.rows, a=actor(), C=u3Cover().T, tild=rows.filter(r=>r.ownerId), kont=rows.filter(k3Worked), dia=rows.filter(r=>['dialog','tilbud'].includes(r.rel)), unw=rows.filter(r=>!k3Worked(r)), mine=a?rows.filter(r=>r.ownerId===a.id):[];
  const M=members(), byM=M.map(m=>m.name+' '+tild.filter(r=>ownKey(r.ownerId)===m.id).length).join(' · ');
  const card=(k,t,v,s,warn)=>'<button type="button" class="k3-card'+(UI.k3.card===k?' on':'')+(warn?' warn':'')+'" data-k3card="'+k+'" aria-pressed="'+(UI.k3.card===k)+'"><span class="k3-ct">'+t+'</span><b>'+v+'</b><small>'+s+'</small></button>';
  return '<div class="k3-cards" role="group" aria-label="Oppsummering. Klikk for å filtrere listen">'+
   '<div class="k3-card plain"><span class="k3-ct">Totalt i målunivers</span><b>'+rows.length+'</b><small>kartlagt av ca. '+nf.format(C.est)+' i markedet</small></div>'+
   card('tildelt','Tildelt',tild.length,rows.length-tild.length+' ufordelt · '+byM)+
   card('kontaktet','Kontaktet',kont.length,rows.length?Math.round(kont.length/rows.length*100)+' % av de kartlagte':'')+
   card('dialog','I aktiv dialog',dia.length,dia.filter(r=>r.rel==='tilbud').length+' med tilbud sendt')+
   card('ikke','Ikke bearbeidet',unw.length+C.unmapped,unw.length+' kartlagt uten kontakt · '+C.unmapped+' ikke kartlagt ennå',true)+
   card('mine','I mitt ansvar',a?mine.length:'–',a?(mine.filter(r=>r.nba.over).length?mine.filter(r=>r.nba.over).length+' har forfalt handling':'ingen forfalt'):'Velg profil øverst til høyre')+'</div>'; }
const k3Dot=n=>'<span class="k3-prog" role="img" aria-label="Bearbeiding: '+U3_MKT[n][1]+'">'+[1,2,3,4,5].map(i=>'<i'+(i<=n?' class="on"':'')+'></i>').join('')+'</span>';
function k3OwnPill(r,can){ const m=ownRef(r.ownerId), n=r.ownerId?ownName(r.ownerId,r.ownerName):'', idx=m?Math.max(0,members(true).findIndex(x=>x.id===m.id))%4:0;
  if(!can) return r.ownerId?'<span class="own3 o'+idx+'"><i>'+esc(initials(n))+'</i><span>'+esc(n)+'</span></span>':'<span class="own3 none"><span>Ufordelt</span></span>';
  return '<label class="own3 '+(r.ownerId?'o'+idx:'none')+'">'+(r.ownerId?'<i aria-hidden="true">'+esc(initials(n))+'</i>':'')+'<span>'+(r.ownerId?esc(n):'Ufordelt')+'</span><select data-k3own="'+esc(r.id)+'" data-k3ownx="'+esc(r.ownerId||'')+'" aria-label="Kundeansvarlig for '+esc(r.name)+'">'+ownOpts(r.ownerId||'')+'</select></label>'; }
function k3Row(r,can){ const K=UI.k3, nb=r.nba, doBtn=nb.k!=='oppgave'&&nb.k!=='ingen'&&U3_ACT[nb.k]?'<button type="button" class="nx3-do" data-k3do="'+esc(nb.k)+':'+esc(r.id)+':'+esc(nb.deal||'')+'">'+esc(U3_ACT[nb.k])+' →</button>':'';
  return '<tr data-korg="'+esc(r.id)+'" tabindex="0"'+(K.sel.has(r.id)?' class="sel"':'')+'>'+(can?'<td class="ck"><input type="checkbox" data-k3sel="'+esc(r.id)+'"'+(K.sel.has(r.id)?' checked':'')+' aria-label="Velg '+esc(r.name)+'"></td>':'')+
   '<td class="org3"><span class="org3-n">'+esc(r.name)+'</span>'+tierChip(r.tier)+'<span class="org3-s">'+esc(r.segment||'Uten segment')+(r.example?'':'')+'</span></td>'+
   '<td><span class="rel r-'+r.rel+'">'+esc(U3_RELN[r.rel])+'</span><span class="mkt3">'+k3Dot(U3_MKT.findIndex(x=>x[0]===r.mkt))+'<em>'+esc(U3_MKTN[r.mkt])+'</em></span></td>'+
   '<td class="own-c">'+k3OwnPill(r,can)+'</td>'+
   '<td class="nx3'+(nb.quiet?' quiet':'')+'"><span class="nx3-a'+(nb.over?' over':'')+'">'+esc(nb.label)+'</span><span class="nx3-w">'+esc(nb.why)+'</span>'+doBtn+'</td>'+
   '<td class="dim3">'+(r.la?'<span>'+esc(ago(r.la))+'</span>'+(r.lastBy?'<span class="k3sub">av '+esc(r.lastBy)+'</span>':''):'<span class="k3sub">Ikke kontaktet</span>')+'</td>'+
   '<td class="dim3 n">'+(r.open?'<span>'+r.open+'</span><span class="k3sub">'+short(r.openVal)+'</span>':'<span class="k3sub">–</span>')+'</td>'+
   '<td class="dim3 n">'+(r.spend?short(r.spend):'<span class="k3sub">–</span>')+'</td></tr>'; }
function k3SegRail(D){ const C=u3Cover(), K=UI.k3;
  return '<div class="k3-rail" role="group" aria-label="Segmenter"><span class="k3-rail-l">Segmenter</span>'+C.segs.filter(k=>k.est>0).map(k=>'<button type="button" class="k3-sg'+(K.seg===k.seg?' on':'')+'" data-k3seg="'+esc(k.seg)+'" aria-pressed="'+(K.seg===k.seg)+'"><span class="k3-sgn">'+esc(k.seg)+'</span><span class="k3-sgv"><b>'+k.allWorked+'</b> av ca. '+k.est+'</span><span class="k3-sgb"><i style="width:'+Math.round(Math.min(1,k.pct)*100)+'%"></i></span></button>').join('')+'</div>'; }
function k3Filters(D){ const K=UI.k3, q=K.q==null?UI.q:K.q, a=actor(), M=members(), seg=(k,n)=>'<button type="button" data-own="'+esc(k)+'" aria-pressed="'+(UI.own===k)+'"'+(k==='mine'&&!a?' disabled title="Velg profil øverst til høyre først"':'')+'>'+esc(n)+'</button>';
  const sel=(id,lab,opts,cur)=>'<label class="k3-f"><span>'+lab+'</span><select class="in fsel" id="'+id+'">'+opts.map(([v,n])=>'<option value="'+esc(v)+'"'+(String(cur)===String(v)?' selected':'')+'>'+esc(n)+'</option>').join('')+'</select></label>';
  return '<div class="k3-filters"><label class="k3-search"><span class="sr">Søk i organisasjoner</span>'+svg('<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>')+'<input class="in" id="k3q" type="search" placeholder="Søk i navn, segment og kontaktpersoner" value="'+esc(q||'')+'"></label>'+
   sel('k3seg','Segment',[['','Alle segmenter'],...SEGMENTS.map(s=>[s,s])],K.seg)+sel('k3rel','Relasjon',[['','Alle'],...U3_REL],K.rel)+sel('k3mkt','Bearbeiding',[['','Alle'],...U3_MKT.filter(x=>x[0]!=='ikke')],K.mkt)+
   '<div class="k3-f"><span>Ansvarlig</span><div class="seg" role="group" aria-label="Ansvarlig">'+seg('alle','Alle')+seg('mine','Kun mine')+M.map(m=>seg(m.id,m.name)).join('')+seg('ufordelt','Ufordelte')+'</div></div>'+
   '<div class="k3-f"><span>Uten kontakt siste</span><div class="seg" role="group" aria-label="Uten kontakt siste">'+[[0,'Alle'],[30,'30 dager'],[60,'60 dager'],[90,'90 dager']].map(([v,n])=>'<button type="button" data-k3quiet="'+v+'" aria-pressed="'+(K.quiet===v)+'">'+n+'</button>').join('')+'</div></div></div>'; }
function k3ListHTML(){ const D=u3Data(), K=UI.k3, can=!readOnly, pred=k3Pred(); let rows=D.rows.filter(pred);
  for(const id of [...K.sel]) if(!rows.some(r=>r.id===id)) K.sel.delete(id);
  const sk=K.sort.k, dir=K.sort.dir, key={pri:r=>k3Pri(r),name:r=>r.name.toLowerCase(),rel:r=>U3_REL.findIndex(x=>x[0]===r.rel),mkt:r=>U3_MKT.findIndex(x=>x[0]===r.mkt),own:r=>(r.ownerId?ownName(r.ownerId):'~')+r.name.toLowerCase(),next:r=>r.task?.due||(r.nba.quiet?'9':'5'),last:r=>r.la||'',open:r=>r.openVal,spend:r=>r.spend};
  rows.sort((a,b)=>{ const x=(key[sk]||key.pri)(a), y=(key[sk]||key.pri)(b); return (x>y?1:x<y?-1:0)*dir||a.name.localeCompare(b.name,'nb'); });
  const th=(k,n,c)=>'<th data-k3sort="'+k+'" tabindex="0"'+(c?' class="'+c+'"':'')+(sk===k?' aria-sort="'+(dir>0?'ascending':'descending')+'"':'')+'>'+n+'</th>', allSel=rows.length>0&&rows.every(r=>K.sel.has(r.id)), M=members();
  const bulk=can&&K.sel.size?'<div class="k3-bulk" role="region" aria-label="Valgte organisasjoner"><b>'+K.sel.size+' valgt</b><span class="k3-bulk-l">Tildel til</span>'+M.map(m=>'<button type="button" class="btn sm" data-k3bulk="'+esc(m.id)+'"'+(K.busy?' disabled':'')+'>'+esc(m.name)+'</button>').join('')+'<button type="button" class="btn ghost sm" data-k3bulk=""'+(K.busy?' disabled':'')+'>Fjern ansvarlig</button><button type="button" class="btn ghost sm" data-k3bulkpark="1"'+(K.busy?' disabled':'')+'>Parkér</button><button type="button" class="btn ghost sm" id="k3SelNo" style="margin-left:auto">Avbryt valg</button></div>':'';
  return k3Cards(D)+k3SegRail(D)+k3Filters(D)+(K.msg?'<div class="notice info" role="status">'+K.msg+' <button type="button" class="lnk" id="k3MsgX">Lukk</button></div>':'')+bulk+
   '<div class="tbl sticky k3-tbl"><table class="k3t"><thead><tr>'+(can?'<th class="ck"><input type="checkbox" id="k3All"'+(allSel?' checked':'')+' aria-label="Velg alle i listen"></th>':'')+th('name','Organisasjon')+th('rel','Relasjon og bearbeiding')+th('own','Ansvarlig')+th('next','Neste steg')+th('last','Siste kontakt','dim3')+th('open','Åpne saker','dim3 n')+th('spend','Forbruk '+(D.Y-1),'dim3 n')+'</tr></thead><tbody>'+
   (rows.length?rows.map(r=>k3Row(r,can)).join(''):'<tr><td colspan="'+(can?8:7)+'" class="empty">Ingen treff med disse filtrene. <button type="button" class="lnk" id="k3Reset">Nullstill filtre</button></td></tr>')+'</tbody></table></div>'+
   '<p class="note">'+rows.length+' av '+D.rows.length+' organisasjoner. Sortert etter '+({pri:'prioritet: prioritet A/B/C, poeng, forfalte handlinger og åpne saker',name:'navn',rel:'relasjon',mkt:'bearbeiding',own:'ansvarlig',next:'neste steg',last:'siste kontakt',open:'åpne saker',spend:'forbruk'})[sk]+'. «Neste steg» er en oppgave når det finnes en, ellers Salongs forslag ut fra det som er registrert. Tildeling er arbeidsfordeling og endrer ikke tilgang.</p>'; }

/* ---------- Markedsdekning: hele målunivers per segment ---------- */
const K3_SER=[['bekr','Bekreftet','var(--accent)'],['tilbud','Tilbud sendt','var(--amber)'],['dialog','I dialog','var(--blue)'],['kont','Kontaktet','var(--violet)'],['uakt','Uaktuell eller parkert','var(--faint)'],['utenKontakt','Kartlagt, ikke kontaktet','color-mix(in srgb,var(--blue) 18%,var(--surface-2))'],['unmapped','Ikke kartlagt','var(--surface-2)']];
function k3CoverHTML(opts){ opts=opts||{}; const own=UI.own!=='alle', C=u3Cover(own?r=>ownMatch(r.ownerId):null), T=C.T, mx=Math.max(1,...C.segs.map(k=>k.est)), who=own?(UI.own==='mine'?'dine':UI.own==='ufordelt'?'ufordelte':ownName(UI.own)+' sine'):'';
  const bar=k=>{ const w=k.est/mx*100; return '<span class="k3-bar" style="width:'+w.toFixed(1)+'%" role="img" aria-label="'+esc(k.seg+': '+K3_SER.map(([f,n])=>k[f]+' '+n.toLowerCase()).join(', ')+', av ca. '+k.est+' i markedet')+'">'+K3_SER.map(([f,n,c])=>k[f]?'<i style="flex:'+k[f]+';background:'+c+'" title="'+esc(n+': '+k[f])+'"></i>':'').join('')+'</span>'; };
  const row=k=>'<tr data-k3cv="'+esc(k.seg)+'"><th scope="row"><button type="button" class="lnk" data-k3golist="'+esc(k.seg)+'">'+esc(k.seg)+'</button><span class="k3sub">ca. '+k.est+' i markedet</span></th><td class="k3-barc">'+bar(k)+'</td><td class="n">'+k.ident+'</td><td class="n">'+(k.kont+k.dialog+k.tilbud+k.bekr+k.uakt)+'</td><td class="n">'+k.dialog+'</td><td class="n">'+k.tilbud+'</td><td class="n"><b>'+k.bekr+'</b></td><td class="n dim3">'+k.uakt+'</td><td class="n"><b class="'+(k.rest/Math.max(1,k.est)>.7?'warnx':'')+'">'+k.rest+'</b></td></tr>';
  return (opts.bare?'':'<div class="k3-covh"><div><h2>Hvor langt har vi kommet i markedet?</h2><p class="note">Målunivers per segment. Antall i markedet er et anslag som kan justeres. Alt annet er regnet fra det som er registrert i Salong.</p></div></div>')+
   '<div class="k3-cover-sum"><div><b>'+T.allWorked+'</b><span>av ca. '+nf.format(T.est)+' aktører er bearbeidet ('+Math.round(T.pct*100)+' %)</span></div><div><b>'+T.rest+'</b><span>gjenstår, hvorav '+T.unmapped+' ikke er kartlagt ennå</span></div><div><b>'+T.bekr+'</b><span>bekreftet · '+T.tilbud+' med tilbud · '+T.dialog+' i dialog</span></div></div>'+
   (opts.noFilter?'':'<div class="k3-filters tight"><div class="k3-f"><span>Vis tall for</span><div class="seg" role="group" aria-label="Ansvarlig">'+[['alle','Alle'],['mine','Mine'],...members().map(m=>[m.id,m.name]),['ufordelt','Ufordelte']].map(([k,n])=>'<button type="button" data-own="'+esc(k)+'" aria-pressed="'+(UI.own===k)+'"'+(k==='mine'&&!actor()?' disabled':'')+'>'+esc(n)+'</button>').join('')+'</div></div>'+(own?'<span class="note">Tallene viser '+esc(who)+' organisasjoner. Anslaget for hele markedet er uendret.</span>':'')+'</div>')+
   '<p class="k3-legend" aria-hidden="true">'+K3_SER.map(([f,n,c])=>'<span><i style="background:'+c+'"></i>'+esc(n)+'</span>').join('')+'</p><div class="tbl"><table class="k3c"><thead><tr><th>Segment</th><th class="k3-barh">Hele markedet</th><th class="n">Kartlagt</th><th class="n">Kontaktet</th><th class="n">I dialog</th><th class="n">Tilbud</th><th class="n">Bekreftet</th><th class="n">Uaktuell</th><th class="n">Gjenstår</th></tr></thead><tbody>'+C.segs.filter(k=>k.est>0).map(row).join('')+'</tbody><tfoot><tr><th scope="row">Alle segmenter</th><td></td><td class="n">'+T.ident+'</td><td class="n">'+(T.kont+T.dialog+T.tilbud+T.bekr+T.uakt)+'</td><td class="n">'+T.dialog+'</td><td class="n">'+T.tilbud+'</td><td class="n">'+T.bekr+'</td><td class="n">'+T.uakt+'</td><td class="n">'+T.rest+'</td></tr></tfoot></table></div>'+
   '<details class="k3-est"><summary>Juster anslaget for hele markedet</summary><p class="note">Antall relevante aktører per segment er et eksempelanslag. Skriv inn ditt eget tall. Tallet lagres i innstillingene og endrer ikke kunder eller saker.</p><div class="k3-estg">'+SEGMENTS.map(s=>'<label class="f"><span>'+esc(s)+'</span><input class="in" type="number" min="0" inputmode="numeric" data-k3est="'+esc(s)+'" value="'+u3Est(s)+'"'+(readOnly?' disabled':'')+'></label>').join('')+'</div></details>'; }

/* ---------- siden ---------- */
VDESC.kontakter='Hvem som er viktigst å jobbe med, hvem som har ansvaret, og hva som er neste steg';
{ const _h=V.kontakter.html, _w=V.kontakter.wire;
  V.kontakter.html=function(){ if(UI.ku.port||UI.ku.legacy) return _h.call(this); const K=UI.k3;
    return '<div class="k3"><div class="k3-top"><div class="seg k3-views" role="tablist" aria-label="Visning">'+[['liste','Kundeliste'],['dekning','Markedsdekning']].map(([k,n])=>'<button type="button" role="tab" data-k3view="'+k+'" aria-selected="'+(K.view===k)+'" aria-pressed="'+(K.view===k)+'">'+n+'</button>').join('')+'</div><div class="k3-top-r"><button class="btn ghost sm" type="button" id="k3Port">Søk i innhold på tvers av kunder</button>'+(readOnly?'':'<button class="btn primary" type="button" id="newOrg">Ny organisasjon</button>')+'</div></div>'+(K.view==='dekning'?k3CoverHTML():k3ListHTML())+'</div>'; };
  V.kontakter.wire=function(v){ if(UI.ku.port||UI.ku.legacy){ _w.call(this,v); return; } const K=UI.k3, rr=()=>renderView(true), keep=id=>{ rr(); if(id){ const el=$('#'+id); if(el){ el.focus(); try{ const l=el.value.length; el.setSelectionRange&&el.setSelectionRange(l,l); }catch(e){} } } };
    $('#newOrg')?.addEventListener('click',()=>openDrawer('org',null)); $('#k3Port')?.addEventListener('click',()=>{ UI.ku.port=true; renderView(true); });
    v.querySelectorAll('[data-k3view]').forEach(b=>b.addEventListener('click',()=>{ K.view=b.dataset.k3view; rr(); }));
    wireOwnFilter(v,rr);
    v.querySelectorAll('[data-k3golist]').forEach(b=>b.addEventListener('click',()=>{ K.view='liste'; K.seg=b.dataset.k3golist; rr(); window.scrollTo(0,0); }));
    v.querySelectorAll('[data-k3est]').forEach(i=>i.addEventListener('change',()=>{ u3Estimate(i.dataset.k3est,i.value); }));
    if(K.view==='dekning') return;
    v.querySelectorAll('[data-k3card]').forEach(b=>b.addEventListener('click',()=>{ K.card=K.card===b.dataset.k3card?'':b.dataset.k3card; if(K.card==='mine'&&actor()) UI.own='alle'; rr(); }));
    v.querySelectorAll('[data-k3seg]').forEach(b=>b.addEventListener('click',()=>{ K.seg=K.seg===b.dataset.k3seg?'':b.dataset.k3seg; rr(); }));
    $('#k3q')?.addEventListener('input',e=>{ K.q=e.target.value.trim(); UI.q=K.q; const h=$('#q'); if(h) h.value=e.target.value; clearTimeout(K.qt); K.qt=setTimeout(()=>keep('k3q'),160); });
    $('#k3seg')?.addEventListener('change',e=>{ K.seg=e.target.value; rr(); }); $('#k3rel')?.addEventListener('change',e=>{ K.rel=e.target.value; rr(); }); $('#k3mkt')?.addEventListener('change',e=>{ K.mkt=e.target.value; rr(); });
    v.querySelectorAll('[data-k3quiet]').forEach(b=>b.addEventListener('click',()=>{ K.quiet=Number(b.dataset.k3quiet); rr(); }));
    $('#k3Reset')?.addEventListener('click',()=>{ Object.assign(K,{q:'',seg:'',rel:'',mkt:'',quiet:0,card:'',tier:''}); UI.q=''; UI.own='alle'; const h=$('#q'); if(h) h.value=''; rr(); });
    $('#k3MsgX')?.addEventListener('click',()=>{ K.msg=''; rr(); });
    v.querySelectorAll('th[data-k3sort]').forEach(t=>{ const f=()=>{ const k=t.dataset.k3sort; K.sort=K.sort.k===k?{k,dir:-K.sort.dir}:{k,dir:['pri','last','open','spend'].includes(k)?-1:1}; rr(); }; t.addEventListener('click',f); t.addEventListener('keydown',e=>{ if(e.key==='Enter'||e.key===' '){ e.preventDefault(); f(); } }); });
    v.querySelectorAll('tr[data-korg]').forEach(r=>{ r.addEventListener('click',()=>openOrg(r.dataset.korg)); r.addEventListener('keydown',e=>{ if(e.key==='Enter'&&e.target===r) openOrg(r.dataset.korg); }); });
    v.querySelectorAll('.ck,.own-c,.nx3-do').forEach(td=>td.addEventListener('click',e=>e.stopPropagation()));
    v.querySelectorAll('[data-k3sel]').forEach(c=>c.addEventListener('change',()=>{ if(c.checked) K.sel.add(c.dataset.k3sel); else K.sel.delete(c.dataset.k3sel); rr(); }));
    $('#k3All')?.addEventListener('change',e=>{ const ids=[...v.querySelectorAll('[data-k3sel]')].map(c=>c.dataset.k3sel); if(e.target.checked) ids.forEach(i=>K.sel.add(i)); else K.sel.clear(); rr(); });
    $('#k3SelNo')?.addEventListener('click',()=>{ K.sel.clear(); rr(); });
    v.querySelectorAll('[data-k3own]').forEach(s=>s.addEventListener('change',async()=>{ const id=s.dataset.k3own, to=s.value||null; s.disabled=true; if(!S.orgs[id]&&PROFILES[id]) await ensureOrg(PROFILES[id]);
      const r=await doAssign({kind:'org',id,to,expect:s.dataset.k3ownx||null});
      toast(r.ok?(r.saved||r.demo?'Kundeansvarlig er nå '+ownName(to)+'.':'Endringen er ikke bekreftet lagret ennå.'):r.conflict?'Kunden fikk ny ansvarlig mens du holdt på ('+ownName(r.current.ownerId)+'). Ingenting er overskrevet.':r.busy?'En annen endrer kunden akkurat nå. Prøv igjen om litt.':(r.error||'Kunden ble ikke endret.')); u3Data.c=null; rr(); }));
    v.querySelectorAll('[data-k3bulk]').forEach(b=>b.addEventListener('click',async()=>{ const ids=[...K.sel], to=b.dataset.k3bulk||null; K.busy=true; rr(); const r=await bulkAssignOrgs(ids,to); K.busy=false; K.sel.clear(); u3Data.c=null;
      K.msg='<b>'+r.ok.length+' '+(r.ok.length===1?'organisasjon':'organisasjoner')+' har fått '+esc(to?ownName(to):'status ufordelt')+(to?' som kundeansvarlig':'')+'.</b>'+(r.fail.length?' '+r.fail.length+' ble ikke endret: '+r.fail.slice(0,3).map(f=>esc((f.name||'')+' ('+f.why+')')).join(', ')+'.':'')+(ids.length-r.ok.length-r.fail.length>0?' '+(ids.length-r.ok.length-r.fail.length)+' hadde allerede denne ansvarlige.':''); rr(); }));
    v.querySelectorAll('[data-k3bulkpark]').forEach(b=>b.addEventListener('click',async()=>{ const ids=[...K.sel]; K.busy=true; rr(); let n=0; for(const id of ids){ if(!S.orgs[id]&&PROFILES[id]) await ensureOrg(PROFILES[id]); const o=S.orgs[id]; if(!o||o.parked) continue; await put('orgs',id,{...o,parked:true,parkedAt:iso(new Date())},{action:'parkert'}); n++; } K.busy=false; K.sel.clear(); u3Data.c=null; K.msg='<b>'+n+' '+(n===1?'organisasjon er':'organisasjoner er')+' parkert.</b> De vises som «Uaktuell / parkert» og kan åpnes igjen fra kundekortet.'; rr(); }));
    v.querySelectorAll('[data-k3do]').forEach(b=>b.addEventListener('click',()=>k3Do(...b.dataset.k3do.split(':')))); };
}
function k3Do(kind,id,dealId){ if(kind==='ring'){ openOrg(id,'aktivitet'); } else if(kind==='epost'){ openOrg(id,'epost'); } else if(kind==='tilbud'||kind==='dato'){ if(dealId) openDrawer('deal',dealId); else openOrg(id); }
  else if(kind==='parker'){ u3Park(id,true).then(()=>{ u3Data.c=null; renderView(true); }); } else if(kind==='gjenapne'){ u3Park(id,false).then(()=>{ u3Data.c=null; renderView(true); }); }
  else if(kind==='tildel'){ (async()=>{ if(!S.orgs[id]&&PROFILES[id]) await ensureOrg(PROFILES[id]); openAssign('org',id); })(); } else openOrg(id); }

/* ---------- kundekortet: neste beste handling, status og lignende aktører ---------- */
function d3Block(D){ const r=D.id?u3Row(D.id):null; if(!r) return ''; const nb=r.nba, R=[['ring','Ring'],['epost','Send e-post'],['tilbud','Følg opp tilbud'],['dato','Foreslå dato'],['tildel','Tildel'],[r.parked?'gjenapne':'parker',r.parked?'Åpne på nytt':'Parkér']].filter(([k])=>k!=='tilbud'||r.openDeals.some(d=>d.stage==='tilbud'||d.stage==='holdt')).filter(([k])=>k!=='dato'||r.openDeals.length);
  const dealOf=k=>(k==='tilbud'?r.openDeals.find(d=>d.stage==='tilbud'||d.stage==='holdt'):r.openDeals.find(d=>!d.date)||r.openDeals[0])||{};
  const sim=u3Similar(r,3);
  return '<section class="kc-sec d3" style="--c:var(--accent)"><h3>Status og neste beste handling</h3><div class="d3-st"><span class="rel r-'+r.rel+'">'+esc(U3_RELN[r.rel])+'</span><span class="mkt3">'+k3Dot(U3_MKT.findIndex(x=>x[0]===r.mkt))+'<em>'+esc(U3_MKTN[r.mkt])+'</em></span><span class="d3-fit" title="Salongs eget anslag, ikke en dokumentert sannhet">Passer Solstad <b>'+r.fit+'</b> · potensial <b>'+r.pot+'</b>'+(r.exp?' · forventet verdi <b>'+short(r.exp)+'</b>':'')+'</span></div>'+
   '<div class="d3-nb'+(nb.over?' over':'')+'"><b>'+esc(nb.label)+'</b><span>'+esc(nb.why)+'</span></div>'+(readOnly?'':'<div class="d3-acts" role="group" aria-label="Handlinger">'+R.map(([k,n])=>'<button type="button" class="btn sm'+(k===nb.k?' primary':'')+'" data-d3do="'+k+':'+esc(r.id)+':'+esc(dealOf(k).id||'')+'">'+n+'</button>').join('')+'</div>')+'</section>'+
   (false&&sim.length&&!readOnly?'<section class="kc-sec d3" style="--c:var(--violet)"><h3>Lignende aktører vi ikke har i målunivers</h3><ul class="d3-sim">'+sim.map(s=>'<li><div><b>'+esc(s.name)+'</b><span>'+esc(s.why.join(' · '))+'</span></div><button type="button" class="btn ghost sm" data-d3add="'+esc(s.name)+'">Legg til</button></li>').join('')+'</ul><p class="note">Forslag fra Salongs eksempeldata. Segment og størrelse er en antakelse og ikke verifisert.</p></section>':''); }
{ const _ko=kcOverview; kcOverview=function(D,o,p,st){ return d3Block(D)+_ko.call(this,D,o,p,st); }; }
document.addEventListener('click',async e=>{ const b=e.target.closest('[data-d3do],[data-d3add]'); if(!b) return;
  if(b.dataset.d3add){ const c=U3_CAT.find(x=>x[0]===b.dataset.d3add); if(c) { await u3Add({name:c[0],segment:c[1]}); u3Data.c=null; if(UI.drawer) renderDrawer(true); renderView(true); } return; }
  const [kind,id,dealId]=b.dataset.d3do.split(':'), D=UI.drawer;
  if(kind==='ring'||kind==='epost'){ if(D){ D.tab=kind==='ring'?'aktivitet':'epost'; renderDrawer(true); } return; }
  if(kind==='parker'||kind==='gjenapne'){ await u3Park(id,kind==='parker'); u3Data.c=null; if(UI.drawer) renderDrawer(true); renderView(true); return; }
  k3Do(kind,id,dealId); });
