/* ---------- Kunnskapslag: «Spør om kunden» og «Forbered samtale» i kundekort og sak ---------- */
function kbScope(D){ return D.kind==='deal'?{orgId:S.deals[D.id].orgId,dealId:D.id}:{orgId:D.id}; }
function kbChip(id){ return '<button type="button" class="kref" data-kbv="'+esc(id)+'">'+esc(id)+'</button>'; }
function kbOpenBtn(op){ if(!op) return ''; if(op.t==='deal'&&S.deals[op.id]) return '<button type="button" class="lnk" data-open="deal:'+op.id+'">Åpne saken</button>'; if(op.t==='org') return '<button type="button" class="lnk" data-open="org:'+op.id+'">Åpne kunden</button>'; if(op.t==='kilder'||op.t==='doc') return '<button type="button" class="lnk" data-kbgo="kilder">Åpne under Kunnskapskilder</button>'; if(op.t==='url') return (op.urls||[]).map(u=>lnk(u)).join(' · '); if(op.t==='market') return '<button type="button" class="lnk" data-mkgo="'+(op.tab||'sammenlign')+'" data-mkv="'+esc(op.venue||'')+'">Åpne i Marked og posisjon</button>'; return ''; }
function kbCalcHTML(B){
  const row=(k,v)=>'<tr><td>'+k+'</td><td>'+v+'</td></tr>', amt=(x,l)=>x?kr(x.kr)+' <span class="meta">('+x.n+' av '+B.rows.length+' rader har '+l+')</span>':'<span class="meta">Ikke i grunnlaget</span>';
  return '<table class="dense kbcalc"><tbody>'+row('Utvalg','Alle rader for kunden i grunnlaget, ikke søketreff')+row('Periode',(B.from||B.to)?esc(fdt(B.from)||'start')+' til '+esc(fdt(B.to)||'nå'):(B.first?'Hele grunnlaget: '+esc(fdt(B.first))+' til '+esc(fdt(B.last)):'Ingen rader'))+row('Statuser som telles',B.statuses.map(s=>BST[s]).join(', '))+
   row('Antall bookinger','<b>'+B.n+'</b>'+(B.series?' · '+B.inSeries+' i '+B.series+' '+(B.series===1?'avtaleserie':'avtaleserier'):''))+row('Ikke talt med','Avbestilt: '+B.by.avbestilt+' · Foreløpig: '+B.by.forelopig+' · Fjernet i kilden: '+B.by.slettet)+
   row('Bookingverdi',amt(B.value,'beløp'))+row('Fakturert',amt(B.invoiced,'fakturert beløp'))+row('Innbetalt',amt(B.paid,'innbetalt beløp'))+
   row('Datadekning',(B.systems.length?B.systems.map(s=>esc(s.name)+': '+s.n+' rader, uttrekk hentet '+esc(fdt(s.extractAt)||'ukjent tidspunkt')+', importert '+esc(fdt(s.importedAt))).join('<br>'):'Ingen bookinguttrekk er importert')+(B.nSalong?'<br>Salong: '+B.nSalong+' bekreftede saker uten treff i uttrekket'+(B.nExample?' ('+B.nExample+' er eksempeldata)':''):'')+(B.review?'<br><span class="st-warn">'+B.review+' rader ligner på kunden, men er ikke koblet og ikke talt</span>':''))+
   row('Samme arrangement to steder',(B.linked?B.linked+' '+(B.linked===1?'booking er':'bookinger er')+' koblet til en sak i Salong og telles én gang. ':'')+(B.suspect?'<span class="st-warn">'+B.suspect+' '+(B.suspect===1?'bekreftet sak har':'bekreftede saker har')+' samme dato som en booking i uttrekket og er ikke koblet. Begge er talt med. Tallet kan være inntil '+B.suspect+' for høyt.</span>':(B.linked?'':'Ingen koblinger og ingen mistenkte dobbeltregistreringer.')))+'</tbody></table>'+
   (B.rows.length?'<details class="kbrows"><summary>Vis de '+B.rows.length+' radene tallene bygger på</summary><table class="dense"><thead><tr><th>Dato</th><th>Arrangement</th><th>Status</th><th>Serie</th><th class="n">Bookingverdi</th><th>Kilde</th></tr></thead><tbody>'+B.rows.map(r=>'<tr><td>'+esc(fdt(r.date))+'</td><td>'+esc(r.title||'')+(r.bookerName||r.invoiceName?'<span class="s">'+[r.bookerName?'Bestiller: '+esc(r.bookerName):'',r.invoiceName?'Fakturamottaker: '+esc(r.invoiceName):''].filter(Boolean).join(' · ')+'</span>':'')+'</td><td>'+BST[r.status]+'</td><td>'+esc(r.seriesId&&!String(r.seriesId).startsWith('sak:')?r.seriesId:r.n>1?r.n+' ganger':'')+'</td><td class="n">'+(r.value!=null?kr(r.value):'<span class="meta">mangler</span>')+'</td><td>'+(r.origin==='uttrekk'?esc(r.sourceSystem)+(r.sourceId?' · '+esc(r.sourceId):'')+(r.dealId&&S.deals[r.dealId]?'<span class="s">Koblet til saken «'+esc(S.deals[r.dealId].title)+'»</span>':''):'Sak i Salong'+(r.example?' (eksempel)':'')+((r.suspect||[]).length?'<span class="s st-warn">Mulig samme som booking i uttrekket</span>':''))+'</td></tr>').join('')+'</tbody></table></details>':'');
}
function kbSrcView(D,id,res){
  const G=res?.G, s=G?.S.find(x=>x.id===id), back='<button type="button" class="btn ghost sm" data-kbv="">← Tilbake til svaret</button>';
  if(s) return '<div class="kbview">'+back+'<h3>'+esc(id)+' · Strukturert oppslag</h3><p>'+esc(s.text)+'</p>'+(s.calc?.t==='bookings'?kbCalcHTML(s.calc.B):'<p class="meta">Hentet fra kunde- og saksfeltene i Salong.</p>')+'<p class="meta">Beregnet '+esc(fdt(iso(G.at)))+' fra data i Salong. Ikke hentet fra bookingsystemet i sanntid.</p></div>';
  const k=G?.K.find(x=>x.id===id)||null;
  const live=k?KB.chunks(G.scope).find(c=>c.id===k.chunkId):null;
  if(!k) return '<div class="kbview">'+back+'<p class="empty">Kilden finnes ikke i dette svaret.</p></div>';
  const row=(a,b)=>'<span>'+a+'</span><b>'+b+'</b>';
  return '<div class="kbview">'+back+'<h3>'+esc(id)+' · '+esc(k.kind)+'</h3>'+(live?'':'<div class="notice warn"><b>Kilden er ikke lenger tilgjengelig.</b> Den er slettet eller flyttet etter at svaret ble laget. Teksten under er slik den var da.</div>')+(live&&live.text!==k.text?'<div class="notice warn"><b>Kilden er endret etter at svaret ble laget.</b> Under vises gjeldende tekst.</div>':'')+
   '<div class="kv">'+row('Kunde',esc(k.shared?'Fellesdokument, gjelder alle':orgName(k.orgId)))+(k.dealId&&S.deals[k.dealId]?row('Sak',esc(S.deals[k.dealId].title)):'')+row('Endret i kilden',esc(fdt(k.changedAt)||'Ikke registrert'))+row(k.chunkId.startsWith('p:')?'Hentet':'Registrert i Salong',esc(fdt(k.regAt)||'Ikke registrert'))+(k.by?row('Av',esc(k.by)):'')+row('Brukt i dette svaret',esc(fdt(iso(res.at))))+'</div>'+
   (k.flags?.unverified?'<p class="meta">Hentet fra åpne kilder. Ikke verifisert av huset.</p>':'')+(k.flags?.history?'<p class="meta">Tilbud er historikk. Gjeldende pris står i prislisten, ikke her.</p>':'')+(k.flags?.expired?'<p class="meta">Dokumentet er merket utgått.</p>':'')+
   '<blockquote class="kbtext">'+esc((live||k).text)+'</blockquote><div class="row">'+kbOpenBtn(k.open)+'</div></div>';
}
function kbPanel(D){
  const scope=kbScope(D), K=D.kb||(D.kb={mode:'brief',q:'',res:null,busy:false,err:'',view:''}), o=S.orgs[scope.orgId], res=K.res, nDocs=kdocs().filter(k=>k.status!=='utgatt').length;
  if(K.view&&res) return kbSrcView(D,K.view,res);
  K.mode='brief';
  let out='<div class="kb"><div class="row kb-top"><h3 class="kb-t">Forbered samtale</h3><button type="button" class="btn sm" data-knopen="'+(scope.dealId?'sak:'+scope.dealId:'kunde:'+scope.orgId)+'">'+(scope.dealId?'Spør om saken':'Spør om kunden')+' i Kunnskap</button></div>'+
   '<p class="meta">Søker bare i <b>'+esc(o.name)+'</b>'+(scope.dealId?' og saken <b>«'+esc(S.deals[scope.dealId].title)+'»</b>':'')+', og i '+nDocs+' godkjente fellesdokumenter. Andre kunder er ikke med.</p>'+
   (K.mode==='ask'?'<form class="kb-ask" id="kbForm"><label class="sr" for="kbQ">Spørsmål om kunden</label><input class="in" id="kbQ" value="'+esc(K.q)+'" placeholder="For eksempel: Hva ble avtalt om teknikk sist?" autocomplete="off"><button class="btn primary" type="submit"'+(K.busy?' disabled':'')+'>'+(K.busy?'Søker …':'Søk i kildene')+'</button></form>':
    '<div class="row"><button class="btn primary" type="button" id="kbBrief"'+(K.busy?' disabled':'')+'>'+(K.busy?'Henter …':res&&res.mode==='brief'?'Oppdater':'Hent grunnlaget')+'</button><span class="meta">Viser status, historikk, uavklarte punkter og neste steg. Virker uten KI.</span></div>')+
   (K.err?'<div class="notice err" role="alert">'+esc(K.err)+'</div>':'')+pinsHTML(scope);
  if(res&&res.mode===K.mode){ const G=res.G, stale=KB.sig(scope)!==res.sig, src=Object.fromEntries(G.K.map(k=>[k.id,k]));
    const claim=c=>'<li><span>'+esc(c.p)+'</span> '+c.k.map(kbChip).join('')+(c.k.find(id=>src[id])?'<q>'+esc(src[c.k.find(id=>src[id])].snippet)+'</q>':'')+'</li>';
    out+=(stale?'<div class="notice warn" role="status"><b>Grunnlaget er endret etter at svaret ble laget kl. '+esc(new Date(res.at).toLocaleTimeString('nb-NO',{hour:'2-digit',minute:'2-digit'}))+'.</b> <button type="button" class="btn sm" data-kbrerun="1">Kjør på nytt</button></div>':'')+
     (res.aiErr?'<div class="notice warn" role="status"><b>KI-oppsummeringen kunne ikke lages.</b> '+esc(res.aiErr)+'</div>':'')+
     (res.ai?'<section class="kb-ai"><div class="rec-h"><span class="rec-tag">KI-oppsummering</span><span class="meta">Avledet av kildene under, laget '+esc(fdt(iso(res.at)))+'. Ikke en egen kilde, og lagres ikke.</span></div>'+
        (res.ai.dok.length?'<h4>Dokumentert</h4><ul class="kb-claims">'+res.ai.dok.map(claim).join('')+'</ul>':'<p class="meta">Ingen påstander kunne dokumenteres i kildene.</p>')+
        (res.ai.unk.length?'<h4>Manglende eller motstridende</h4><ul class="kb-claims">'+res.ai.unk.map(claim).join('')+'</ul>':'')+
        (res.ai.sug.length?'<h4>Forslag til neste handling</h4><ul class="kb-claims sug">'+res.ai.sug.map(claim).join('')+'</ul>':'')+
        (res.ai.dropped.length?'<p class="meta">'+res.ai.dropped.length+' '+(res.ai.dropped.length===1?'påstand':'påstander')+' ble fjernet fordi de manglet gyldig kilde eller hadde tall som ikke står i kilden.</p>':'')+'</section>':
      (sample?'<div class="row"><button class="btn sm" type="button" data-kbai="1"'+(K.busy?' disabled':'')+'>Lag KI-oppsummering av grunnlaget</button><span class="meta">Valgfritt. Grunnlaget under er komplett uten.</span></div>':'<p class="meta">KI er ikke tilgjengelig. Du ser hele grunnlaget under.</p>'))+
     '<section class="kb-sec"><h4>Dokumentert i strukturerte data</h4><ul class="kb-facts">'+G.S.map(s=>'<li><span>'+esc(s.text)+'</span> '+kbChip(s.id)+'</li>').join('')+'</ul></section>'+
     '<section class="kb-sec"><h4>'+(res.mode==='ask'?'Utdrag som passer spørsmålet':'Siste registrerte kilder')+' <span class="cnt3">'+G.K.length+'</span></h4>'+(G.K.length?'<ol class="kb-hits">'+G.K.map(k=>'<li><div class="kb-hd">'+kbChip(k.id)+'<b>'+esc(k.kind)+'</b><span class="meta">'+[k.dealId&&S.deals[k.dealId]?'«'+esc(S.deals[k.dealId].title)+'»':'',k.changedAt?'endret '+esc(fdt(k.changedAt)):'tidspunkt ikke registrert',k.by?esc(k.by):''].filter(Boolean).join(' · ')+'</span>'+(k.flags?.unverified?'<span class="src open">Ikke verifisert</span>':'')+(k.flags?.old?'<span class="src inf">Eldre versjon</span>':'')+(k.flags?.expired?'<span class="src inf">Utgått</span>':'')+'</div><p>'+esc(k.snippet)+'</p></li>').join('')+'</ol>':'<p class="empty">'+(res.mode==='ask'?'Ikke funnet i tilgjengelig grunnlag. Det betyr ikke at det aldri har skjedd, bare at det ikke står i kildene Salong har ('+G.searched+' tekster gjennomsøkt).':'Ingen notater, e-poster eller tilbud er registrert på kunden.')+'</p>')+'</section>'+
     '<section class="kb-sec"><h4>Manglende eller motstridende <span class="cnt3">'+G.gaps.length+'</span></h4>'+(G.gaps.length?'<ul class="kb-gaps">'+G.gaps.map(g=>'<li><span class="cst c-'+(g.kind==='motstridende'?'motstridende':'mangler')+'">'+(g.kind==='motstridende'?'⚠ Motstridende':'○ Mangler')+'</span> '+esc(g.text)+' '+kbOpenBtn(g.open)+'</li>').join('')+'</ul>':'<p class="empty">Ingen funnet av reglene i Salong.</p>')+'</section>'+
     '<section class="kb-sec"><h4>Neste handling <span class="cnt3">'+G.next.length+'</span></h4>'+(G.next.length?'<ul class="kb-gaps">'+G.next.map(n=>'<li><span class="src '+(n.kind==='oppgave'?'crm':'inf')+'">'+(n.kind==='oppgave'?'Oppgave':'Forslag')+'</span> '+esc(n.text)+' '+kbOpenBtn(n.open)+'</li>').join('')+'</ul>':'<p class="empty">Ingen oppgaver eller forslag.</p>')+(PROFILES[scope.orgId]&&!scope.dealId?'<div class="kc-rec"><div class="rec-h"><span class="rec-tag">Anbefalt vinkling</span><span class="meta">Avledet. Ikke verifisert, og ikke brukt som kilde.</span></div><p>'+esc(PROFILES[scope.orgId].angle||'')+'</p></div>':'')+'</section>'+
     '<section class="kb-sec"><h4>Grunnlag og ferskhet</h4><p class="meta">Gjennomsøkt: '+G.searched+' tekster for kunden og fellesdokumenter. Ordbasert søk. Svaret ble hentet '+esc(fdt(iso(res.at)))+'.</p><p class="meta"><b>Ikke tilgjengelig:</b> '+G.unavailable.map(esc).join(' · ')+'.</p><p class="meta">'+esc(KB.live().reason)+'</p></section>'; }
  return out+'</div>';
}
function wireKb(root,D){
  root.querySelectorAll('[data-knopen]').forEach(b=>b.addEventListener('click',()=>{ const [t,id]=b.dataset.knopen.split(':'); openKunnskap(t==='sak'?{t:'sak',dealId:id}:{t:'kunde',orgId:id}); }));
  root.querySelectorAll('[data-kbsrc]').forEach(b=>b.addEventListener('click',async()=>{ const scope=kbScope(D); D.kb=D.kb||{mode:'brief',q:'',res:null,busy:false,err:'',view:''}; if(D.kind==='deal') D.dtab='kunnskap'; else D.tab='kunnskap';
    const G=kbGround(scope,''); const c=KB.chunks(scope).find(x=>x.id===b.dataset.kbsrc); if(c&&!G.K.some(k=>k.chunkId===c.id)) G.K.unshift({id:'K0',...c,chunkId:c.id,snippet:c.text.slice(0,300)}); D.kb.mode='brief'; D.kb.res={mode:'brief',q:'',G,ai:null,aiErr:'',sig:G.sig,at:G.at}; D.kb.view=c?(G.K.find(k=>k.chunkId===c.id).id):''; if(!c) toast('Kilden er ikke lenger tilgjengelig.'); renderDrawer(true); }));
  if(!root.querySelector('.kb,.kbview')) return; const K=D.kb, scope=kbScope(D);
  root.querySelectorAll('[data-kbm]').forEach(b=>b.addEventListener('click',()=>{ K.mode=b.dataset.kbm; K.err=''; renderDrawer(true); if(K.mode==='ask') $('#kbQ')?.focus(); }));
  $('#kbQ')?.addEventListener('input',e=>{ K.q=e.target.value; });
  $('#kbForm')?.addEventListener('submit',e=>{ e.preventDefault(); if(!K.q.trim()){ toast('Skriv et spørsmål.'); return; } kbRun(D,scope,'ask',K.q.trim(),false); });
  $('#kbBrief')?.addEventListener('click',()=>kbRun(D,scope,'brief','',false));
  root.querySelectorAll('[data-kbai]').forEach(b=>b.addEventListener('click',()=>kbRun(D,scope,K.mode,K.q.trim(),true)));
  root.querySelectorAll('[data-kbrerun]').forEach(b=>b.addEventListener('click',()=>kbRun(D,scope,K.res.mode,K.res.q,!!K.res.ai)));
  root.querySelectorAll('[data-kbv]').forEach(b=>b.addEventListener('click',()=>{ K.view=b.dataset.kbv; renderDrawer(true); root.querySelector('.body')?.scrollTo(0,0); }));
  root.querySelectorAll('[data-kbgo]').forEach(b=>b.addEventListener('click',()=>{ closeDrawer(); if(!UI.drawer){ UI.dsec='kilder'; go('data'); } }));
}
/* ---------- Kunnskapskilder (Data og oppsett) ---------- */
function kbSources(){
  const imps=Object.values(S.imports||{}).filter(r=>r.type==='bookings'&&!r.rolledBack).sort((a,b)=>b.at.localeCompare(a.at)), bySys={};
  for(const r of imps) if(!bySys[r.system]) bySys[r.system]=r;
  const nB=bookingsAll().length, L=[];
  L.push({n:'Salong (kontakter, saker, aktiviteter, tilbud)',st:db?'ok':'proto',lbl:db?'Tilkoblet':'Kun prototype',last:db?(SYNC.lastSaved?'Sist bekreftet lagret '+SYNC.lastSaved.toLocaleTimeString('nb-NO',{hour:'2-digit',minute:'2-digit'}):'Ingen endringer lagret i denne økten'):'Demo, lagres ikke',err:SYNC.err&&SYNC.queue.size?'Siste lagring feilet. '+SYNC.queue.size+' endringer venter':''});
  if(Object.keys(bySys).length) for(const [sys,r] of Object.entries(bySys)) L.push({n:'Bookinguttrekk: '+sys,st:'cfg',lbl:'Uttrekk, ikke sanntid',last:'Uttrekk hentet '+(fdt(r.extractAt)||'ukjent')+' · importert '+fdt(r.at)+' av '+(r.by||'ukjent')+' · '+bookingsAll().filter(b=>b.sourceSystem===sys).length+' bookinger',err:r.errors?r.errors+' rader hadde feil og ble ikke importert':''});
  else L.push({n:'Bookinguttrekk (CSV)',st:'off',lbl:'Ikke importert',last:'Ingen uttrekk er importert',err:''});
  L.push({n:'Bookingsystemet direkte',st:'off',lbl:'Utilgjengelig',last:'Ingen dokumentert integrasjon. Aktuell ledighet og reservasjoner kan ikke slås opp',err:''});
  L.push({n:'Økonomi (fakturert og innbetalt)',st:'off',lbl:'Utilgjengelig',last:bookingsAll().some(b=>b.invoiced!=null||b.paid!=null)?'Bare kolonnene som fulgte med bookinguttrekket':'Ikke i grunnlaget',err:''});
  L.push({n:'E-post',st:'off',lbl:'Utilgjengelig',last:'Appen kan bare lage utkast. Innhold kommer inn når noen limer inn eller logger en e-post',err:''});
  L.push({n:'Åpne kilder (profiler)',st:'cfg',lbl:'Statisk',last:'Hentet september 2026. Oppdateres ikke automatisk. Ikke verifisert av huset',err:''});
  L.push({n:'Godkjente fellesdokumenter',st:kdocs().length?'ok':'off',lbl:kdocs().length?kdocs().filter(k=>k.status!=='utgatt').length+' gjeldende':'Ingen lagt inn',last:kdocs().length?'Sist godkjent '+fdt(kdocs().map(k=>k.approvedAt||'').sort().pop()):'',err:''});
  L.push({n:'Søkeindeks',st:'proto',lbl:'Bygges i nettleseren',last:'Bygges på nytt fra kildene ved hvert søk. Lagres ikke. Ordbasert søk, ikke vektorsøk',err:''});
  return L;
}
UI.kd={title:'',kind:'Prisliste',validFrom:'',text:''};
function kbSourcesHTML(){
  const rev=bookingsAll().filter(b=>!b.orgId), F=UI.kd, opts=orgs().sort((a,b)=>a.name.localeCompare(b.name,'nb'));
  return '<h2>Kunnskapskilder</h2><p class="note">Hva «Spør om kunden», «Forbered samtale» og Saksbildet bygger på. Hver kilde har sin egen status. At én kilde er oppdatert, betyr ikke at de andre er det.</p>'+
   '<table class="dense"><thead><tr><th>Kilde</th><th>Status</th><th>Sist oppdatert</th><th>Feil</th></tr></thead><tbody>'+kbSources().map(s=>'<tr><td class="name">'+esc(s.n)+'</td><td><span class="ist '+s.st+'">'+esc(s.lbl)+'</span></td><td class="s2">'+esc(s.last)+'</td><td class="s2">'+(s.err?'<span class="st-err">'+esc(s.err)+'</span>':'Ingen registrert')+'</td></tr>').join('')+'</tbody></table>'+
   '<h3 class="sub3">Bookinger til gjennomgang <span class="cnt3">'+rev.length+'</span></h3>'+(rev.length?'<p class="note">Disse ble importert uten sikker kunde. De er ikke med i noen kundes tall før et menneske har koblet dem.</p><table class="dense"><thead><tr><th>Arrangør i kilden</th><th>Dato</th><th>Forslag</th><th>Koble til</th><th></th></tr></thead><tbody>'+rev.map(b=>'<tr><td>'+esc(b.organizerName)+(b.orgnr?'<span class="s">Org.nr. '+esc(b.orgnr)+'</span>':'')+'</td><td>'+esc(fdt(b.date))+'</td><td>'+(b.suggestOrgId&&S.orgs[b.suggestOrgId]?'Ligner på «'+esc(orgName(b.suggestOrgId))+'»':'Ingen')+'</td><td><select class="in fsel" data-revsel="'+b.id+'" aria-label="Velg kunde for '+esc(b.organizerName)+'"><option value="">Velg kunde</option>'+opts.map(o=>'<option value="'+o.id+'"'+(b.suggestOrgId===o.id?' selected':'')+'>'+esc(o.name)+'</option>').join('')+'</select></td><td><button class="btn sm" type="button" data-revok="'+b.id+'">Koble</button></td></tr>').join('')+'</tbody></table>':'<p class="empty">Ingen bookinger venter på gjennomgang.</p>')+
   kbDupHTML()+
   '<h3 class="sub3">Godkjente fellesdokumenter</h3><p class="note">Dokumenter som gjelder alle kunder, for eksempel prisliste og leievilkår. De søkes sammen med kundens egne kilder. Legg bare inn det som er godkjent.</p>'+
   (kdocs().length?'<table class="dense"><thead><tr><th>Dokument</th><th>Type</th><th>Gjelder fra</th><th>Godkjent</th><th></th></tr></thead><tbody>'+kdocs().map(k=>'<tr><td class="name">'+esc(k.title)+'</td><td>'+esc(k.kind)+'</td><td>'+esc(fdt(k.validFrom)||'Ikke oppgitt')+'</td><td>'+esc(fdt(k.approvedAt))+' av '+esc(k.approvedBy||'ukjent')+'</td><td>'+(k.status==='utgatt'?'<span class="note">Utgått</span>':'<button class="btn ghost sm" type="button" data-kdexp="'+k.id+'">Merk som utgått</button>')+'</td></tr>').join('')+'</tbody></table>':'<p class="empty">Ingen fellesdokumenter er lagt inn.</p>')+
   '<div class="form"><label class="f"><span>Tittel</span><input class="in" id="kdTitle" value="'+esc(F.title)+'"></label><label class="f"><span>Type</span><select class="in" id="kdKind">'+['Prisliste','Leievilkår','Rutine','Annet'].map(k=>'<option'+(F.kind===k?' selected':'')+'>'+k+'</option>').join('')+'</select></label><label class="f"><span>Gjelder fra</span><input class="in" type="date" id="kdFrom" value="'+esc(F.validFrom)+'"></label><label class="f full"><span>Tekst</span><textarea class="in" id="kdText" rows="5" placeholder="Lim inn teksten i dokumentet">'+esc(F.text)+'</textarea></label></div><div class="row"><button class="btn" type="button" id="kdAdd">Legg til som godkjent av meg</button><span class="note">Du står som den som godkjente dokumentet.</span></div>';
}
function kbDupHTML(){
  const P=KB.dupPairs(), L=bookingsAll().filter(b=>b.dealId&&S.deals[b.dealId]&&!S.deals[b.dealId].deletedAt), bk=id=>S.bookings[id]||{};
  return '<h3 class="sub3">Samme arrangement i uttrekk og i Salong <span class="cnt3">'+P.length+'</span></h3><p class="note">En bekreftet sak i Salong og en booking i uttrekket telles som ett arrangement bare når noen har koblet dem her. Salong slår dem aldri sammen på egen hånd. Lik dato hos samme kunde vises under som mulig dobbeltregistrering.</p>'+
   (P.length?'<table class="dense"><thead><tr><th>Kunde</th><th>Booking i uttrekket</th><th>Sak i Salong</th><th></th></tr></thead><tbody>'+P.map(x=>{ const b=bk(x.bookingId), d=S.deals[x.dealId]; return '<tr><td class="name">'+esc(orgName(x.orgId))+'</td><td>'+esc(b.title||'Booking')+'<span class="s">'+esc(fdt(b.date))+' · '+esc(b.sourceSystem||'')+(b.sourceId?' · '+esc(b.sourceId):'')+' · '+esc(BST[b.status]||'')+'</span></td><td>'+esc(d.title)+'<span class="s">'+esc(fdt(d.date))+' · '+esc(roomName(d.room))+'</span></td><td><div class="row"><button class="btn sm" type="button" data-dupok="'+esc(x.bookingId+'|'+x.dealId)+'">Samme arrangement, koble</button><button class="btn ghost sm" type="button" data-dupno="'+esc(x.bookingId+'|'+x.dealId)+'">Ikke samme</button></div></td></tr>'; }).join('')+'</tbody></table>':'<p class="empty">Ingen mulige dobbeltregistreringer funnet.</p>')+
   (L.length?'<table class="dense"><thead><tr><th>Koblet booking</th><th>Sak</th><th>Koblet av</th><th></th></tr></thead><tbody>'+L.map(b=>'<tr><td>'+esc(b.title||'Booking')+'<span class="s">'+esc(fdt(b.date))+(b.sourceId?' · '+esc(b.sourceId):'')+'</span></td><td>'+esc(S.deals[b.dealId].title)+'</td><td class="s2">'+esc(b.linkBy||'Ikke registrert')+(b.linkAt?' · '+esc(fdt(b.linkAt)):'')+'</td><td><button class="btn ghost sm" type="button" data-dupun="'+esc(b.id)+'">Fjern kobling</button></td></tr>').join('')+'</tbody></table>':'');
}
function wireKbSources(v){
  v.querySelectorAll('[data-dupok]').forEach(b=>b.addEventListener('click',async()=>{ const [bid,did]=b.dataset.dupok.split('|'), bk=S.bookings[bid]; if(!bk||!S.deals[did]) return; await put('bookings',bid,{...bk,dealId:did,linkBy:me.name||'',linkById:me.id||null,linkAt:iso(new Date())}); toast('Koblet. Arrangementet telles én gang.'); renderView(true); }));
  v.querySelectorAll('[data-dupno]').forEach(b=>b.addEventListener('click',async()=>{ const [bid,did]=b.dataset.dupno.split('|'), bk=S.bookings[bid]; if(!bk) return; await put('bookings',bid,{...bk,notDeal:[...(bk.notDeal||[]),did]}); toast('Registrert som to ulike arrangementer.'); renderView(true); }));
  v.querySelectorAll('[data-dupun]').forEach(b=>b.addEventListener('click',async()=>{ const bk=S.bookings[b.dataset.dupun]; if(!bk) return; const {dealId,linkBy,linkById,linkAt,...rest}=bk; await put('bookings',b.dataset.dupun,rest); toast('Koblingen er fjernet.'); renderView(true); }));
  const F=UI.kd; [['kdTitle','title'],['kdKind','kind'],['kdFrom','validFrom'],['kdText','text']].forEach(([id,k])=>$('#'+id)?.addEventListener('input',e=>{ F[k]=e.target.value; }));
  $('#kdAdd')?.addEventListener('click',async()=>{ if(!F.title.trim()||!F.text.trim()){ toast('Tittel og tekst må fylles ut.'); return; } await put('kdocs',uid('k'),{title:F.title.trim(),kind:F.kind,validFrom:F.validFrom,text:F.text.trim(),status:'gjeldende',approvedBy:me.name||'',approvedAt:iso(new Date())}); UI.kd={title:'',kind:'Prisliste',validFrom:'',text:''}; toast('Dokumentet er lagt til'); renderView(true); });
  v.querySelectorAll('[data-kdexp]').forEach(b=>b.addEventListener('click',async()=>{ const k=S.kdocs[b.dataset.kdexp]; if(k){ await put('kdocs',b.dataset.kdexp,{...k,status:'utgatt',expiredAt:iso(new Date())}); renderView(true); } }));
  v.querySelectorAll('[data-revok]').forEach(b=>b.addEventListener('click',async()=>{ const id=b.dataset.revok, sel=v.querySelector('[data-revsel="'+id+'"]').value, bk=S.bookings[id]; if(!sel){ toast('Velg kunden først.'); return; } await put('bookings',id,{...bk,orgId:sel,match:'manuell',suggestOrgId:null,matchedBy:me.name||'',matchedAt:iso(new Date())}); toast('Koblet til '+orgName(sel)); renderView(true); }));
}

/* ---------- Porteføljesøk: uttrykkelig egen funksjon i Kunder ---------- */
function portHTML(){
  const q=UI.q, R=q?KB.search(q,{all:true,shared:false},20):{hits:[],searched:0};
  return '<div class="filters"><button type="button" class="tgl" id="kPort" aria-pressed="true">Søk i innhold på tvers av kunder</button><span class="note">Porteføljesøk. Søker i notater, e-poster og tilbud for alle kunder i Salong. Skriv i søkefeltet øverst.</span></div>'+
   (q?(R.hits.length?'<section class="panel"><header><h2>'+R.hits.length+' treff for «'+esc(q)+'»</h2><span class="sub">'+R.searched+' tekster gjennomsøkt, ordbasert søk</span></header><ol class="kb-hits">'+R.hits.map(k=>'<li data-port="'+esc(k.orgId)+'"><div class="kb-hd"><b>'+esc(orgName(k.orgId))+'</b><span class="src inf">'+esc(k.kind)+'</span><span class="meta">'+(k.changedAt?'endret '+esc(fdt(k.changedAt)):'tidspunkt ikke registrert')+'</span></div><p>'+esc(k.snippet)+'</p></li>').join('')+'</ol></section>':'<p class="empty">Ikke funnet i tilgjengelig grunnlag ('+R.searched+' tekster gjennomsøkt). Det betyr ikke at det aldri har skjedd.</p>'):'<p class="empty">Skriv et søkeord i feltet øverst.</p>');
}
{ const _h=V.kontakter.html, _w=V.kontakter.wire, BTN='<button type="button" class="tgl" id="kPort" aria-pressed="false">Søk i innhold på tvers av kunder</button>';
  V.kontakter.html=function(){ if(UI.ku.port) return portHTML(); return _h.call(this).replace('Uten dialog siste 30 dager</button>','Uten dialog siste 30 dager</button>'+BTN); };
  V.kontakter.wire=function(v){ if(!UI.ku.port) _w.call(this,v); $('#kPort')?.addEventListener('click',()=>{ UI.ku.port=!UI.ku.port; renderView(true); }); v.querySelectorAll('[data-port]').forEach(li=>li.addEventListener('click',()=>openOrg(li.dataset.port,'kunnskap'))); }; }

/* ---------- Om Salong: kunnskapslaget, kartlegging og avklaringer ---------- */
function kbPlanHTML(){
  const R={real:'Laget',mock:'Eksempel',local:'Kun i nettleser',todo:'Krever backend'}, row=(t,n,d)=>'<tr><td><span class="tag '+t+'">'+R[t]+'</span></td><td class="name">'+n+'</td><td class="s2">'+d+'</td></tr>';
  return '<section class="panel"><header><h2>Kunnskapslaget</h2><span class="sub">Hva som er laget, og hva som venter på backend og leverandør</span></header><table class="dense arch"><tbody>'+
   row('real','Strukturert bookinghistorikk','Regnes fra alle kundens rader, med periode, statuser og datadekning synlig. Bookingverdi, fakturert og innbetalt holdes adskilt. Samme kilde-ID oppdaterer samme rad.')+
   row('real','Import av bookinguttrekk','Kilde-ID, versjon og tidsstempler bevares. Eldre rader overskriver ikke nyere. Usikre navn går til gjennomgang, ikke automatisk kobling.')+
   row('real','Tekstsøk med kildehenvisning','Ordbasert søk i kundens notater, innlimte e-poster, tilbud og godkjente fellesdokumenter. Avgrenset til én kunde. Porteføljesøk er en egen funksjon under Kunder.')+
   row('real','Kunnskap-fanen','Én chatflate over det samme kunnskapslaget, med valg av grunnlag: én kunde, én sak, hele CRM-et eller markedskunnskap. Uten KI heter det «Søk i kilder».')+
   row('real','Kontroll av KI-svar','Fakta må ha et ordrett sitat som finnes i kilden. Tall i beregninger sjekkes mot en ny utregning. Påstander som ikke består, fjernes før visning. Kontrollen er ordbasert, ikke en vurdering av mening.')+
   row('local','Samtalehistorikk','Samtalen ligger bare i nettleserens minne og forsvinner når siden lukkes. Den lagres ikke og søkes ikke i.')+
   row('local','Tilgangskontroll','Avgrensningen til én kunde skjer i nettleseren. Det er ikke sikkerhet. Alle med tilgang til siden har tilgang til alle data.')+
   row('local','Søkeindeks','Bygges i nettleseren fra kildene hver gang. Ingen innbygging, ingen vektorsøk.')+
   row('todo','Direkte oppslag i bookingsystemet','Ikke koblet. Ledighet og aktive reservasjoner vises aldri som bekreftet.')+
   row('todo','E-post og dokumentarkiv','Appen leser ikke e-post. Bare tekst som limes inn eller logges, er søkbar.')+
   row('todo','Tilgang per bruker og sletting i indeks','Krever innlogging, roller og en indeks på serveren.')+'</tbody></table>'+
   '<h3 class="sub3">Må avklares før neste steg</h3><ul class="om-list"><li><b>Bookingsystemet:</b> hvilket system det er, om leverandøren har et dokumentert API, om det støtter lesing av ledighet og reservasjoner, og om endringer kan varsles eller må hentes periodisk.</li><li><b>Nøkler i bookingsystemet:</b> om bookinger har et varig nummer, om kunder har en kunde-ID, og om organisasjonsnummer er registrert.</li><li><b>Serier:</b> hvordan systemet skiller en avtaleserie fra de enkelte bookingene, og hvordan avbestillinger og slettinger vises i et uttrekk.</li><li><b>Økonomi:</b> hvor fakturert og innbetalt beløp finnes, og om de kan kobles til bookingnummer.</li><li><b>Personvern:</b> hvilke kilder som kan indekseres, til hvilket formål, og hvem som godkjenner det. Private e-postkasser er ikke med som standard.</li><li><b>Roller:</b> hvem som skal se hvilke kunder, tilbud og beløp.</li></ul></section>';
}
{ const _om2=V.om.html; V.om.html=function(){ return _om2.call(this)+kbPlanHTML(); }; }
