/* ---------- Marked og posisjon: Oversikt, Sammenligning og Segmentfit ----------
   Oversikten er forhåndsregnet fra researchgrunnlaget (MKSEED) og fra Salongs egne saker. Dokumentert og vurdert holdes fra hverandre.
   Segmentfit bygger på u3.js. Passform, potensial og forventet verdi er Salongs egne anslag. */
UI.mk.tab='oversikt'; UI.m3={col:'rel',seg:'',sub:'sammenlign'};
const M3_TABS=[['oversikt','Oversikt'],['sammenlign','Sammenligning'],['segmentfit','Segmentfit']];
const M3_RC={tidligere:'#8a6d3b',aktiv:'#7aa83a',prioritert:'#6b4fa3',prospekt:'#9a9a90',dialog:'#2f6f9f',tilbud:'#b7791f',bekreftet:'#14301a'};
const M3_OC=['#265B00','#2f6f9f','#6b4fa3','#b7791f'];
const m3Cap=v=>(v.capacities||{}).theatre??null;
const m3Med=a=>{ const s=[...a].sort((x,y)=>x-y); return s.length?s[Math.floor((s.length-1)/2)]:null; };
const m3Src=ids=>(ids||[]).slice(0,2).map(id=>mpSrcA(id)).filter(Boolean).join(' · ');

function m3Stats(){ const F=mpV('solstad'), all=MKSEED.venues, ext=all.filter(v=>!v.own), withCap=all.filter(v=>m3Cap(v)!=null).sort((a,b)=>m3Cap(b)-m3Cap(a)), rank=withCap.findIndex(v=>v.id==='solstad')+1;
  const cap=m3Cap(F), bigger=ext.filter(v=>m3Cap(v)!=null&&m3Cap(v)>cap), atLeast300=ext.filter(v=>m3Cap(v)!=null&&m3Cap(v)>=300), extCap=ext.filter(v=>m3Cap(v)!=null);
  const room=ext.filter(v=>mpPrice(v,'room').y!=null), day=ext.filter(v=>mpPrice(v,'day').y!=null), noPrice=ext.filter(v=>!mpUsable(v));
  const nfF=mpNF(F), medNf=m3Med(ext.map(mpNF)), feat=Object.keys(MS_FEAT).map(k=>({k,n:MS_FEAT[k],f:mpFeat(F,k,'day')}));
  const inc=feat.filter(x=>['ink','pak'].includes(x.f.s)), extra=feat.filter(x=>['til','avk'].includes(x.f.s));
  const sd=dealsOp().filter(d=>d.room==='solstad'&&d.stage!=='tapt'), won=sd.filter(d=>d.stage==='bekreftet'), open=sd.filter(d=>OPEN.includes(d.stage));
  const own=all.filter(v=>v.own&&mpUsable(v)&&mpPrice(v,'room').y!=null).sort((a,b)=>(m3Cap(b)||0)-(m3Cap(a)||0));
  return {F,cap,rank,nCap:withCap.length,bigger,atLeast300,extCap,room,day,noPrice,ext,nfF,medNf,feat,inc,extra,won,open,sd,own}; }

function m3Over(){ const s=m3Stats(), F=s.F, C=u3Cover().T, W=u3White().slice(0,3), ins=[];
  ins.push({k:'dok',t:'Solstad er blant de største lokalene i utvalget',b:'Solstad rommer '+s.cap+' i stolrader, nummer '+s.rank+' av '+s.nCap+' lokaler med oppgitt kapasitet. Bare '+s.atLeast300.length+' av '+s.extCap.length+' eksterne lokaler med oppgitt kapasitet rommer 300 eller flere'+(s.atLeast300.length?': '+s.atLeast300.map(v=>mpLabel(v)+' ('+m3Cap(v)+')').join(', '):'')+'.',src:F.source_ids});
  ins.push({k:'dok',t:'Solstad har ingen publisert pris ennå',b:'Av '+s.ext.length+' eksterne lokaler har '+s.room.length+' en publisert romleie (eks. mva) og '+s.day.length+' en publisert dagpakke (inkl. mva). Disse kan ikke sammenlignes direkte. '+s.noPrice.length+' eksterne mangler brukbar pris og må innhentes. Nærmeste egne prisanker er '+(s.own[0]?s.own[0].name+' ('+m3Cap(s.own[0])+' plasser, '+nf.format(mpPrice(s.own[0],'room').y)+' kr eks. mva)':'ikke tilgjengelig')+'.',src:['lh_terms']});
  ins.push({k:'dok',t:'Leveransen er i hovedsak tillegg',b:'Av seks leveranseområder er '+s.inc.length+' dokumentert som inkludert eller i pakke for Solstad'+(s.inc.length?' ('+s.inc.map(x=>x.n.toLowerCase()).join(', ')+')':'')+'. '+s.extra.length+' er tillegg eller må avklares ('+s.extra.map(x=>x.n.toLowerCase()).join(', ')+'). Eksterne lokaler dokumenterer typisk '+(s.medNf==null?'–':s.medNf)+' av seks.',src:F.source_ids});
  ins.push({k:'dok',t:'Hele 4. etasje og mulig kombinasjon med 3. etasje',b:'Begge fløyer brukes ved '+s.cap+' i stolrader, og 3. etasje kan leies i tillegg til grupperom og pauser. Det gir en bredere pakke enn et enkeltrom, men separate flater må vurderes i hvert tilfelle.',src:['lh_solstad']});
  ins.push({k:'vurd',t:'Etterspørselen i eget CRM er tidlig',b:s.sd.length?s.sd.length+' saker gjelder Solstad: '+s.won.length+' bekreftet (verdi '+short(s.won.reduce((a,d)=>a+dval(d),0))+') og '+s.open.length+' åpne (vektet '+short(s.open.reduce((a,d)=>a+dval(d)*ST[d.stage].p,0))+'). Det er for tidlig til å si noe sikkert om hvilke segmenter som velger Solstad.':'Ingen saker gjelder Solstad ennå.',src:[]});
  const strong=['Størrelse: '+s.cap+' i stolrader, nr '+s.rank+' av '+s.nCap+' i utvalget. Bare '+s.bigger.length+' eksterne lokaler er større.','Samlet flate: hele 4. etasje, med mulighet for 3. etasje.','Rigg og oppsett inngår normalt i leien, ifølge leievilkårene.'],
    weak=['Ingen publisert pris. Prisen må settes før den kan sammenlignes.','Teknikk, bemanning, strømming og servering er tillegg og må prises etter behov.','Åpner februar 2027. Ledighet og reservasjoner er ikke i grunnlaget.'],
    flekk=[...W.map(k=>k.seg+': bare '+k.allWorked+' av ca. '+k.est+' bearbeidet, og passform '+k.sf+' for Solstad.'),s.noPrice.length+' eksterne lokaler mangler brukbar pris i utvalget.','Beliggenhet og reisetid er ikke registrert for noen lokaler.'];
  const insH=ins.map((x,i)=>'<article class="m3-in"><span class="m3-n">'+(i+1)+'</span><div><h3>'+esc(x.t)+'</h3><p>'+esc(x.b)+'</p><span class="m3-tag '+x.k+'">'+(x.k==='dok'?'Dokumentert':'Salongs vurdering')+'</span>'+(m3Src(x.src)?'<span class="m3-src">'+m3Src(x.src)+'</span>':'')+'</div></article>').join('');
  const list=(c,t,L)=>'<section class="m3-box '+c+'"><h3>'+t+'</h3><ul>'+L.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul></section>';
  return '<div class="m3"><section class="m3-hero"><div class="m3-hero-h"><div><span class="m3-eyebrow">Solstad i markedet</span><h2>'+esc(F.name)+' · '+s.cap+' plasser i stolrader</h2><p class="note">Forhåndsregnet fra researchgrunnlaget ('+MKSEED.venues.length+' lokaler, kontrollert '+esc(fdt(MKSEED.checked_on))+') og egne saker. Et utvalg, ikke hele markedet.</p></div><div class="row"><button type="button" class="btn primary" data-m3ask="marked">Spør Innsikt om markedet</button></div></div>'+
     '<div class="m3-kpi"><div><b>'+s.cap+'</b><span>stolrader · nr '+s.rank+' av '+s.nCap+'</span></div><div><b>'+((F.capacities||{}).classroom||'–')+'</b><span>klasserom</span></div><div><b>'+(F.area_m2||'–')+' m²</b><span>areal</span></div><div><b>'+esc(F.planned_opening?new Date(F.planned_opening+'-01').toLocaleDateString('nb-NO',{month:'long',year:'numeric'}):'–')+'</b><span>planlagt åpning</span></div><div><b>'+Math.round(C.pct*100)+' %</b><span>av målunivers bearbeidet</span></div></div></section>'+
     '<section class="m3-sec"><div class="m3-sech"><h2>Fem innsikter</h2><span class="note">Dokumentert er hentet fra kilder med kontrolldato. Vurdering er Salongs egen tolkning.</span></div><div class="m3-ins">'+insH+'</div></section>'+
     '<div class="m3-cols">'+list('good','Styrker',strong)+list('bad','Svakheter',weak)+list('gap','Hvite flekker',flekk)+'</div>'+
     '<section class="m3-sec m3-val"><h3>Verdigrunnlag</h3><p>'+esc(LH_VERDI.vis)+'</p><p class="note">'+esc(LH_VERDI.note)+'</p></section>'+
     '<div class="row m3-go"><button type="button" class="btn" data-mktab="segmentfit">Se segmentfit og prioritering</button><button type="button" class="btn ghost" data-mktab="sammenlign">Sammenlign med alternativene</button></div></div>'; }

/* ---------- Sammenligning: dimensjonsstatus + tabell eller kart ---------- */
function m3Dims(){ const s=m3Stats(), n=MKSEED.venues.length, cov=k=>MKSEED.venues.filter(v=>MP_DOC.includes(mpFeat(v,k,'day').s)).length, capN=MKSEED.venues.filter(v=>m3Cap(v)!=null).length, prN=MKSEED.venues.filter(mpUsable).length;
  return [['Pris',prN+' av '+n+' lokaler har brukbar pris. Romleie (eks. mva) og dagpakke (inkl. mva) blandes aldri.',prN/n],['Kapasitet',capN+' av '+n+' har oppgitt plasser i stolrader. Oppsett holdes adskilt.',capN/n],['Fleksibilitet',cov('setup')+' av '+n+' dokumenterer rigg og oppsett, '+cov('breakout')+' grupperom.',(cov('setup')+cov('breakout'))/(2*n)],['Teknikk',cov('av')+' av '+n+' dokumenterer lyd og bilde, '+cov('stream')+' strømming.',(cov('av')+cov('stream'))/(2*n)],['Mat og drikke',cov('food')+' av '+n+' dokumenterer servering.',cov('food')/n],['Beliggenhet','Ikke registrert i grunnlaget.',0],['Bruksområde','Salongs egen grovsortering i fire kategorier. Ikke leverandørens betegnelse.',.5]]; }
function m3Sub(t){ return '<div class="m3-sub" role="group" aria-label="Visning">'+[['sammenlign','Side om side'],['posisjonering','Kart: kapasitet og pris']].map(([k,n])=>'<button type="button" data-mktab="'+k+'" aria-pressed="'+(t===k)+'">'+n+'</button>').join('')+'</div>'; }
function m3DimHTML(){ return '<section class="m3-dims" aria-label="Hva sammenligningen dekker"><h3>Hva sammenligningen dekker</h3><div class="m3-dg">'+m3Dims().map(([n,t,f])=>'<div class="m3-d"><b>'+n+'</b><span class="m3-db" role="img" aria-label="Dekning '+Math.round(f*100)+' prosent"><i style="width:'+Math.round(f*100)+'%"></i></span><small>'+esc(t)+'</small></div>').join('')+'</div></section>'; }

/* ---------- Segmentfit ---------- */
function m3Pts(){ const D=u3Data(), S3=UI.m3, hash=id=>{ let h=0; for(const c of id) h=(h*31+c.charCodeAt(0))>>>0; return h; };
  return D.rows.filter(r=>r.rel!=='parkert'&&(!S3.seg||r.segment===S3.seg)&&ownMatch(r.ownerId)).map(r=>({r,x:Math.min(100,Math.max(0,r.fit))+((hash(r.id)%7)-3)*.35,y:Math.min(100,Math.max(0,r.pot))+((hash(r.id+'y')%7)-3)*.35})); }
function m3PrioSVG(P){ const S3=UI.m3, W=760,H=440,L=46,R=14,T=14,B=44, lo=a=>Math.max(0,Math.floor((Math.min(...a)-6)/10)*10), x0=lo(P.map(p=>p.x)), y0=lo(P.map(p=>p.y)), X=v=>L+(W-L-R)*(v-x0)/(100-x0), Y=v=>T+(H-T-B)*(1-(v-y0)/(100-y0)), mx=Math.max(1,...P.map(p=>p.r.exp)), rad=e=>5+Math.sqrt(e/mx)*11, owners=members(true), oc=id=>{ if(!id) return '#9a9a90'; const i=Math.max(0,owners.findIndex(m=>m.id===ownKey(id))); return M3_OC[i%4]; };
  const col=p=>S3.col==='own'?oc(p.r.ownerId):(M3_RC[p.r.rel]||'#9a9a90'), top=[...P].sort((a,b)=>b.r.exp-a.r.exp).slice(0,8).map(p=>p.r.id), mxX=X(Math.max(x0+5,62)), myY=Y(Math.max(y0+5,55));
  const circ=[...P].sort((a,b)=>b.r.exp-a.r.exp).map(p=>{ const cx=X(p.x), cy=Y(p.y), r=rad(p.r.exp); return '<g class="m3-pt" tabindex="0" role="button" data-m3org="'+esc(p.r.id)+'" aria-label="'+esc(p.r.name+', '+U3_RELN[p.r.rel]+', passform '+p.r.fit+', potensial '+p.r.pot+', forventet verdi '+short(p.r.exp))+'"><circle cx="'+cx.toFixed(1)+'" cy="'+cy.toFixed(1)+'" r="'+r.toFixed(1)+'" fill="'+col(p)+'" fill-opacity=".62" stroke="'+col(p)+'" stroke-width="1.5"/><title>'+esc(p.r.name+' · '+U3_RELN[p.r.rel]+' · '+(p.r.ownerId?ownName(p.r.ownerId,p.r.ownerName):'Ufordelt')+' · passform '+p.r.fit+', potensial '+p.r.pot+(p.r.exp?', forventet '+short(p.r.exp):''))+'</title></g>'; }).join('');
  const lab=P.filter(p=>top.includes(p.r.id)).map(p=>(X(p.x)>W*.72?'<text class="m3-lb" text-anchor="end" x="'+(X(p.x)-rad(p.r.exp)-4).toFixed(1)+'" y="'+(Y(p.y)+4).toFixed(1)+'">':'<text class="m3-lb" x="'+(X(p.x)+rad(p.r.exp)+4).toFixed(1)+'" y="'+(Y(p.y)+4).toFixed(1)+'">')+esc(p.r.name.length>22?p.r.name.slice(0,21)+'…':p.r.name)+'</text>').join('');
  const tk=(a)=>[0,1,2,3,4].map(i=>Math.round(a+(100-a)*i/4)), ticks=tk(x0).map(t=>'<text class="m3-tk" x="'+X(t)+'" y="'+(H-B+16)+'" text-anchor="middle">'+t+'</text><line class="m3-gl" x1="'+X(t)+'" x2="'+X(t)+'" y1="'+T+'" y2="'+(H-B)+'"/>').join('')+tk(y0).map(t=>'<text class="m3-tk" x="'+(L-8)+'" y="'+(Y(t)+4)+'" text-anchor="end">'+t+'</text><line class="m3-gl" x1="'+L+'" x2="'+(W-R)+'" y1="'+Y(t)+'" y2="'+Y(t)+'"/>').join('');
  return '<svg viewBox="0 0 '+W+' '+H+'" class="m3-svg" role="group" aria-label="Prioriteringsflate: passform for Solstad mot kommersielt potensial. '+P.length+' organisasjoner.">'+ticks+
    '<rect class="m3-q" x="'+mxX+'" y="'+T+'" width="'+(W-R-mxX)+'" height="'+(myY-T)+'"/><text class="m3-ql" x="'+(W-R-8)+'" y="'+(T+18)+'" text-anchor="end">Prioriter nå</text><text class="m3-ql dim" x="'+(L+8)+'" y="'+(T+18)+'">Utvikle: høyt potensial, lavere passform</text><text class="m3-ql dim" x="'+(W-R-8)+'" y="'+(H-B-10)+'" text-anchor="end">God passform, lavere verdi</text><text class="m3-ql dim" x="'+(L+8)+'" y="'+(H-B-10)+'">Lav prioritet</text>'+
    '<line class="m3-ax" x1="'+mxX+'" x2="'+mxX+'" y1="'+T+'" y2="'+(H-B)+'"/><line class="m3-ax" x1="'+L+'" x2="'+(W-R)+'" y1="'+myY+'" y2="'+myY+'"/>'+circ+lab+
    '<text class="m3-at" x="'+((L+W-R)/2)+'" y="'+(H-6)+'" text-anchor="middle">Passform for Solstad (0 til 100, Salongs anslag)</text><text class="m3-at" transform="translate(12 '+((T+H-B)/2)+') rotate(-90)" text-anchor="middle">Kommersielt potensial (0 til 100)</text></svg>'; }
function m3PrioHTML(){ const S3=UI.m3, P=m3Pts(), segs=u3Cover().segs.filter(k=>k.est>0).map(k=>k.seg), owners=members(true);
  const legend=S3.col==='own'?[...owners.map((m,i)=>[M3_OC[i%4],m.name]),['#9a9a90','Ufordelt']]:U3_REL.filter(([k])=>k!=='parkert').map(([k,n])=>[M3_RC[k],n]);
  const nPri=P.filter(p=>p.r.fit>=62&&p.r.pot>=55&&!['bekreftet','tilbud'].includes(p.r.rel)).length;
  return '<section class="m3-sec"><div class="m3-sech"><div><h2>Prioriteringsflate <span class="note">Salongs vurdering</span></h2><p class="note">Hver sirkel er en organisasjon. Til høyre er passformen for Solstad best, øverst er det kommersielle potensialet størst. Sirkelens størrelse viser forventet verdi. Alle tre er Salongs egne anslag, ikke dokumentert.</p></div></div>'+
    '<div class="m3-ctl"><div class="m3-f"><span>Farge etter</span><div class="seg" role="group" aria-label="Farge etter">'+[['rel','Status'],['own','Ansvarlig']].map(([k,n])=>'<button type="button" data-m3col="'+k+'" aria-pressed="'+(S3.col===k)+'">'+n+'</button>').join('')+'</div></div><label class="m3-f"><span>Segment</span><select class="in fsel" id="m3Seg"><option value="">Alle segmenter</option>'+segs.map(s=>'<option'+(S3.seg===s?' selected':'')+'>'+esc(s)+'</option>').join('')+'</select></label><div class="m3-f"><span>Ansvarlig</span>'+ownFilterHTML('Ansvarlig')+'</div></div>'+
    '<p class="m3-sum"><b>'+P.length+'</b> organisasjoner vist · <b>'+nPri+'</b> i «Prioriter nå» uten tilbud eller bekreftet avtale</p>'+(P.length?'<div class="m3-svgw">'+m3PrioSVG(P)+'</div>':'<p class="empty">Ingen organisasjoner passer filteret.</p>')+
    '<p class="k3-legend m3-lg" aria-hidden="true">'+legend.map(([c,n])=>'<span><i style="background:'+c+'"></i>'+esc(n)+'</span>').join('')+'</p><p class="note">'+esc(LH_VERDI.note)+'</p></section>'; }
function m3SegTable(){ const C=u3Cover().segs.filter(k=>k.est>0), R=C.map(k=>({k,f:u3SegFit(k.seg),sp:u3Seg(k.seg)})).sort((a,b)=>b.f.fit-a.f.fit), cls=f=>f>=65?'good':f>=45?'mid':'low', tx=f=>f>=65?'Passer godt':f>=45?'Passer middels':'Passer mindre';
  const row=({k,f,sp})=>'<tr><th scope="row"><b>'+esc(k.seg)+'</b><span class="k3sub">'+esc(sp.ev||'')+'</span></th><td><span class="m3-fit '+cls(f.fit)+'"><i style="width:'+f.fit+'%"></i></span><span class="m3-ft '+cls(f.fit)+'">'+tx(f.fit)+' · '+f.fit+'</span></td><td class="n">'+f.att[0]+'–'+f.att[1]+'</td><td class="n">'+Math.round(k.pct*100)+' %</td><td class="n">'+short(sp.val)+'</td><td class="m3-why">'+esc(f.att[1]<U3_SOLSTAD.min?'Typisk for lite for Solstad ('+U3_SOLSTAD.min+'–'+U3_SOLSTAD.max+').':f.att[0]>U3_SOLSTAD.max?'Typisk for stort for Solstad.':f.size>=80?'Størrelsen treffer Solstad.':'Delvis overlapp i størrelse.')+(f.evid!=null?' '+f.solDeals+' av '+f.solTot+' Solstad-saker kommer herfra.':'')+'</td></tr>';
  return '<section class="m3-sec"><div class="m3-sech"><div><h2>Hvilke segmenter passer Solstad?</h2><p class="note">Passform bygger på typisk deltakerantall og arrangementstype mot Solstads '+U3_SOLSTAD.min+'–'+U3_SOLSTAD.max+' plasser, og på egne Solstad-saker når det finnes nok. Størrelse per segment er Salongs antakelse.</p></div></div><div class="tbl"><table class="k3c m3-t"><thead><tr><th>Segment og typiske arrangementer</th><th>Passform for Solstad</th><th class="n">Gjester typisk</th><th class="n">Bearbeidet</th><th class="n">Typisk verdi</th><th>Hvorfor</th></tr></thead><tbody>'+R.map(row).join('')+'</tbody></table></div></section>'; }
function m3SimHTML(){ const L=u3SimilarToBest(6), U=u3Under().slice(0,3);
  return '<div class="m3-cols two"><section class="m3-box"><h3>Lignende aktører vi ikke har</h3>'+(L.length?'<ul class="m3-sim">'+L.map(s=>'<li><div><b>'+esc(s.name)+'</b><span>'+esc(s.segment)+' · ligner på '+esc(s.likeness.slice(0,2).join(' og '))+'</span></div>'+(readOnly?'':'<button type="button" class="btn ghost sm" data-d3add="'+esc(s.name)+'">Legg til</button>')+'</li>').join('')+'</ul><p class="note">Forslag fra Salongs eksempelkatalog, bare navn. Ikke verifisert, og segment og størrelse er en antakelse.</p>':'<p class="empty">Ingen forslag akkurat nå.</p>')+'</section>'+
    '<section class="m3-box"><h3>Underrepresentert i kundebasen</h3>'+(U.length?'<ul class="m3-und">'+U.map(u=>'<li><b>'+esc(u.seg)+'</b><span>'+Math.round(u.mkt*100)+' % av markedet, '+Math.round(u.own*100)+' % av kundene ('+u.cust+' kunder)</span></li>').join('')+'</ul><p class="note">Sammenligner segmentets andel av anslått marked med andelen av dagens og tidligere kunder.</p>':'<p class="empty">Kundebasen speiler markedet godt nok til at ingen segmenter skiller seg ut.</p>')+'</section></div>'; }
function m3Seg(){ const W=u3White().slice(0,4);
  return '<div class="m3"><section class="m3-sec"><div class="m3-sech"><div><h2>Hvite flekker</h2><p class="note">Segmenter der passformen er høy og få er bearbeidet.</p></div></div><div class="m3-wh">'+W.map(k=>'<div class="m3-w"><b>'+esc(k.seg)+'</b><span>Passform '+k.sf+' · '+Math.round(k.pct*100)+' % bearbeidet</span><span class="m3-wb" role="img" aria-label="'+Math.round(k.pct*100)+' prosent bearbeidet"><i style="width:'+Math.min(100,Math.round(k.pct*100))+'%"></i></span><small>'+k.allWorked+' av ca. '+k.est+' · '+k.rest+' gjenstår</small></div>').join('')+'</div></section>'+
    m3PrioHTML()+m3SegTable()+m3SimHTML()+'<p class="note m3-ft">Antall identifiserte, kontaktklare og adresserte per segment står i <button type="button" class="lnk" data-m3tomal="1">Prospekter → Målmarked</button>.</p></div>'; }

V.marked.html=function(){ const M=UI.mk, t=M.tab, top=t==='posisjonering'?'sammenlign':t;
  const tabs='<div class="m3-tabs"><div class="seg mk-tabs" role="tablist" aria-label="Marked og posisjon">'+M3_TABS.map(([k,n])=>'<button type="button" role="tab" data-mktab="'+k+'" aria-selected="'+(top===k)+'" aria-pressed="'+(top===k)+'">'+n+'</button>').join('')+'</div><button type="button" class="lnk" data-mktab="laering"'+(t==='laering'?' aria-current="true"':'')+'>Læring fra saker</button></div>';
  const body=t==='oversikt'?m3Over():t==='segmentfit'?m3Seg():t==='sammenlign'?m3DimHTML()+m3Sub(t)+mcHTML():t==='posisjonering'?m3DimHTML()+m3Sub(t)+mpPosHTML():mkLearnHTML();
  return '<div class="mk">'+tabs+body+'</div>'; };
{ const _w=V.marked.wire; V.marked.wire=function(v){ _w.apply(this,arguments); const rr=()=>{ const y=window.scrollY; renderView(true); window.scrollTo(0,y); };
  v.querySelectorAll('[data-m3tomal]').forEach(b=>b.addEventListener('click',()=>{ UI.mt.tab='mal'; go('prosp'); }));
  v.querySelectorAll('[data-m3ask]').forEach(b=>b.addEventListener('click',()=>{ UI.kn.sc={t:'marked',orgId:'',dealId:''}; if(UI.kn.turns.length) knNew({t:'marked',orgId:'',dealId:''}); askOpenPanel(UI.kn.sc,true); }));
  v.querySelectorAll('[data-m3col]').forEach(b=>b.addEventListener('click',()=>{ UI.m3.col=b.dataset.m3col; rr(); }));
  $('#m3Seg')?.addEventListener('change',e=>{ UI.m3.seg=e.target.value; rr(); });
  v.querySelectorAll('[data-m3org]').forEach(g=>{ const open=()=>openOrg(g.dataset.m3org); g.addEventListener('click',open); g.addEventListener('keydown',e=>{ if(e.key==='Enter'||e.key===' '){ e.preventDefault(); open(); } }); });
  if(UI.mk.tab==='segmentfit'){ wireOwnFilter(v,rr); v.querySelectorAll('[data-k3golist]').forEach(b=>b.addEventListener('click',()=>{ UI.k3.view='liste'; UI.k3.seg=b.dataset.k3golist; go('kontakter'); })); v.querySelectorAll('[data-k3est]').forEach(i=>i.addEventListener('change',()=>{ u3Estimate(i.dataset.k3est,i.value); })); }
  }; }
